import type { Concept } from './types'

// Conceptual, textbook-level content only. No pricing, no specific
// entitlements, no invented product behavior. Volatile items (licensing,
// exam status) carry an explicit verification note in the UI via
// <VerifyBadge/>, not inline fabricated numbers.
//
// dependsOn / usedBy only encode the safe, explicitly-documented
// relationships called out in the build spec (see project README). Do not
// add undocumented service dependencies here.

export const concepts: Concept[] = [
  // ───────────────────────── FOUNDATION ─────────────────────────
  {
    id: 'client-server',
    name: 'Client/Server Model',
    domain: 'foundation',
    mapLayer: 'business',
    purpose: 'Describes how a requesting device (client) consumes a service hosted by another system (server).',
    definition:
      'A client/server model divides work between a client that requests a service and a server that provides it, over a network connection.',
    problemSolved: 'Lets many clients share centralized services, data, and management instead of each device running everything locally.',
    dependsOn: [],
    usedBy: ['directory-services', 'application'],
    projectRelevance: ['Frames whether a workload is being centralized, decentralized, or moved to a hosted service during a project.'],
    pmQuestions: ['Is this workload moving from client-hosted to server/cloud-hosted, or the reverse?'],
    commonTerms: ['client', 'server', 'request/response'],
    retrievalPrompt: 'What problem does separating client and server responsibilities solve?',
    relatedConcepts: ['application', 'network'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'endpoint-device',
    name: 'Endpoint',
    domain: 'foundation',
    mapLayer: 'endpoint',
    purpose: 'The device a user interacts with — laptop, desktop, phone, or tablet.',
    definition: 'An endpoint is a physical device that connects to a network and is used, managed, and secured as an individual unit.',
    problemSolved: 'Gives IT a discrete unit to enroll, configure, patch, and secure.',
    dependsOn: [],
    usedBy: ['intune', 'compliance-policy', 'conditional-access'],
    projectRelevance: ['Endpoint count and device state often gate rollout pacing and support load.'],
    pmQuestions: ['How many endpoints are in scope, and are they corporate-owned, BYOD, or mixed?'],
    retrievalPrompt: 'Why does endpoint state matter before enforcing stricter access policy?',
    relatedConcepts: ['intune', 'mdm', 'compliance-policy'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'operating-system',
    name: 'Operating System',
    domain: 'foundation',
    mapLayer: 'endpoint',
    purpose: 'The software layer that manages hardware resources and runs applications on a device or server.',
    definition: 'An operating system (OS) manages hardware, memory, storage, and processes, and provides the platform applications run on.',
    problemSolved: 'Provides a consistent platform so applications do not each manage hardware directly.',
    dependsOn: [],
    usedBy: ['application', 'endpoint-device'],
    projectRelevance: ['OS version and support lifecycle can be a hard prerequisite for endpoint or security tooling.'],
    pmQuestions: ['Are all in-scope devices on a supported OS version before rollout?'],
    relatedConcepts: ['endpoint-device', 'application'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'network',
    name: 'Network',
    domain: 'foundation',
    mapLayer: 'azure',
    purpose: 'The infrastructure that connects devices and services so they can exchange data.',
    definition: 'A network is the set of connected devices, links, and protocols that let systems communicate.',
    problemSolved: 'Without a network, distributed systems (client/server, cloud, hybrid) cannot exchange data.',
    dependsOn: [],
    usedBy: ['ip-addressing', 'dns', 'vnet'],
    projectRelevance: ['Network design and access are frequent external dependencies (ISPs, MSPs, firewalls) in a migration.'],
    pmQuestions: ['Who owns the network changes required, and what is their change lead time?'],
    relatedConcepts: ['vnet', 'dns', 'ip-addressing'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'ip-addressing',
    name: 'IP Addressing',
    acronym: 'IP',
    domain: 'foundation',
    mapLayer: 'azure',
    purpose: 'The numeric addressing scheme that identifies devices on a network.',
    definition: 'An IP address uniquely identifies a device on a network so traffic can be routed to and from it.',
    problemSolved: 'Enables routing of traffic between specific devices across a network.',
    dependsOn: ['network'],
    usedBy: ['dns', 'vnet'],
    projectRelevance: ['IP ranges and overlaps matter when connecting on-prem networks to Azure VNets.'],
    pmQuestions: ['Do the on-prem and cloud IP ranges overlap, and who resolves that if so?'],
    relatedConcepts: ['network', 'vnet', 'dns'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'dns',
    name: 'DNS',
    acronym: 'Domain Name System',
    domain: 'foundation',
    mapLayer: 'operations',
    purpose: 'Translates human-readable domain names into IP addresses and publishes service records.',
    definition: 'DNS resolves domain names to IP addresses and hosts records (MX, TXT, CNAME, SRV) that services use to verify domain ownership and route traffic such as email.',
    problemSolved: 'Lets services be found and verified by name instead of memorized IP addresses, and lets mail and identity systems prove domain ownership.',
    dependsOn: ['network'],
    usedBy: ['exchange-online', 'entra-id'],
    projectRelevance: [
      'Third-party DNS ownership (registrar or external MSP) is a common external dependency in Microsoft 365 migrations.',
      'DNS record changes are frequently part of migration cutover for mail routing and domain verification.',
      'Access, credentials, and change lead time for the DNS zone must be confirmed early — not assumed.',
    ],
    pmQuestions: [
      'Who has administrative access to the DNS zone, and what is their standard change lead time?',
      'What is the validation and rollback plan if a DNS change does not propagate as expected?',
    ],
    analogy: 'Less like a fixed address book and more like a directory service that must be kept current as things move.',
    analogyLabel: 'Conceptual analogy, not a technical definition',
    retrievalPrompt: 'Why is DNS often a scheduling risk in a migration project rather than a technical risk?',
    scenarioNote: 'Do not assume every DNS change causes downtime or has a fixed propagation time — this varies by record type, TTL, and provider.',
    relatedConcepts: ['exchange-online', 'entra-id', 'network'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'directory-services',
    name: 'Directory Services',
    domain: 'foundation',
    mapLayer: 'identity',
    purpose: 'A structured store of identities (users, groups, devices) used to authenticate and authorize access.',
    definition: 'A directory service stores and organizes identity objects and their attributes so systems can look up and validate them.',
    problemSolved: 'Provides a single authoritative place to manage identity instead of per-system accounts.',
    dependsOn: [],
    usedBy: ['ad-ds', 'entra-id'],
    projectRelevance: ['The directory model (on-prem, cloud, or hybrid) shapes nearly every identity and access decision in a project.'],
    pmQuestions: ['Is there a single authoritative directory, or multiple directories that must be reconciled?'],
    relatedConcepts: ['ad-ds', 'entra-id', 'hybrid-identity'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'authentication',
    name: 'Authentication',
    domain: 'foundation',
    mapLayer: 'identity',
    purpose: 'Verifying that a user or system is who it claims to be.',
    definition: 'Authentication is the process of proving identity, typically with a credential such as a password, certificate, or token, often combined with a second factor.',
    problemSolved: 'Prevents unverified users or systems from accessing resources.',
    dependsOn: ['directory-services'],
    usedBy: ['mfa', 'sso', 'conditional-access'],
    projectRelevance: ['Authentication method changes (adding MFA, enabling SSO) affect every user and typically need a pilot and help-desk readiness.'],
    pmQuestions: ['What authentication methods are in use today, and what changes for end users?'],
    retrievalPrompt: 'How does authentication differ from authorization?',
    relatedConcepts: ['authorization', 'mfa', 'sso'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'authorization',
    name: 'Authorization',
    domain: 'foundation',
    mapLayer: 'identity',
    purpose: 'Determining what an authenticated user or system is allowed to do.',
    definition: 'Authorization is the process of granting or denying access to specific resources or actions once identity has been established.',
    problemSolved: 'Limits what a verified identity can access, based on role or policy, rather than granting blanket access.',
    dependsOn: ['authentication'],
    usedBy: ['rbac', 'least-privilege'],
    projectRelevance: ['Authorization models (RBAC, least privilege) drive access reviews and role design work during a project.'],
    pmQuestions: ['Who owns the access model, and is it being redesigned as part of this project or carried over as-is?'],
    relatedConcepts: ['authentication', 'rbac', 'least-privilege'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'application',
    name: 'Application',
    domain: 'foundation',
    mapLayer: 'workloads',
    purpose: 'Software that performs tasks for users, often relying on other services (database, API, identity).',
    definition: 'An application is a software program that delivers functionality to users, typically composed of a front end, logic, and data layer.',
    problemSolved: 'Delivers business functionality on top of infrastructure and platform services.',
    dependsOn: ['operating-system', 'database', 'api'],
    usedBy: [],
    projectRelevance: ['Unknown application dependencies are a leading cause of migration surprises — discovery work exists specifically to surface them.'],
    pmQuestions: ['Has application dependency discovery been completed, or is it assumed complete?'],
    relatedConcepts: ['api', 'database', 'discover-phase'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'database',
    name: 'Database',
    domain: 'foundation',
    mapLayer: 'azure',
    purpose: 'A structured system for storing and retrieving data used by applications.',
    definition: 'A database stores structured data and provides mechanisms to query, update, and secure it, on-premises or in the cloud.',
    problemSolved: 'Gives applications a reliable, queryable place to persist data instead of ad hoc storage.',
    dependsOn: [],
    usedBy: ['application'],
    projectRelevance: ['Data migration adds compatibility, downtime, and validation requirements that differ from a simple lift-and-shift.'],
    pmQuestions: ['What is the source database version, and has compatibility with the target been assessed?'],
    relatedConcepts: ['application', 'backup', 'rpo'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'api',
    name: 'API',
    acronym: 'Application Programming Interface',
    domain: 'foundation',
    mapLayer: 'workloads',
    purpose: 'A defined way for software components to communicate with each other.',
    definition: 'An API is a contract that lets one piece of software request functionality or data from another in a defined, predictable way.',
    problemSolved: 'Lets systems integrate without each one needing to know the internal implementation of the other.',
    dependsOn: [],
    usedBy: ['application'],
    projectRelevance: ['Custom integrations built against an API can break silently during a platform migration if not inventoried.'],
    pmQuestions: ['What integrations depend on this system, and who owns each one?'],
    relatedConcepts: ['application'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'logs',
    name: 'Logs / Logging',
    domain: 'foundation',
    mapLayer: 'operations',
    purpose: 'Records of system and user activity used for troubleshooting, auditing, and security monitoring.',
    definition: 'Logs are time-stamped records of events generated by systems, applications, or services.',
    problemSolved: 'Gives visibility into what happened, when, and by whom — required for troubleshooting and security investigation.',
    dependsOn: [],
    usedBy: ['azure-monitor', 'sentinel', 'service-health'],
    projectRelevance: ['Validation steps in a cutover plan often rely on reviewing logs to confirm success before declaring completion.'],
    pmQuestions: ['What log source will be used to validate this change worked as intended?'],
    relatedConcepts: ['azure-monitor', 'sentinel'],
    sourceIds: ['az900-governance'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'backup',
    name: 'Backup',
    domain: 'foundation',
    mapLayer: 'operations',
    purpose: 'A copy of data kept so it can be restored after loss or corruption.',
    definition: 'A backup is a stored copy of data or system state, taken so it can be restored if the original is lost, corrupted, or needs to be rolled back.',
    problemSolved: 'Provides a recovery point when data is lost, corrupted, or a change needs to be undone.',
    dependsOn: [],
    usedBy: ['rpo', 'disaster-recovery'],
    projectRelevance: ['No cutover plan should proceed without a confirmed, tested backup and rollback path.'],
    pmQuestions: ['Has the backup been verified as restorable, not just as having completed?'],
    relatedConcepts: ['rpo', 'rto', 'rollback'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'high-availability',
    name: 'High Availability',
    acronym: 'HA',
    domain: 'foundation',
    mapLayer: 'azure',
    purpose: 'Designing a system to keep running through component failure with minimal disruption.',
    definition: 'High availability is an architecture goal where a system continues operating, typically via redundancy, despite the failure of individual components.',
    problemSolved: 'Reduces the impact of a single component failure on overall service availability.',
    dependsOn: [],
    usedBy: ['disaster-recovery'],
    projectRelevance: ['HA requirements can affect architecture decisions, cost, and the acceptance criteria for a migrated workload.'],
    pmQuestions: ['What availability target does the business actually require, and is it documented?'],
    relatedConcepts: ['disaster-recovery', 'azure-regions'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'disaster-recovery',
    name: 'Disaster Recovery',
    acronym: 'DR',
    domain: 'foundation',
    mapLayer: 'azure',
    purpose: 'The plan and capability to restore systems and data after a major disruption.',
    definition: 'Disaster recovery is the set of policies, tools, and procedures used to recover system functionality after an outage or disaster.',
    problemSolved: 'Gives the organization a defined path back to operation after a significant failure, rather than an ad hoc response.',
    dependsOn: ['backup', 'high-availability'],
    usedBy: [],
    projectRelevance: ['A DR plan and its RPO/RTO targets should be documented before a migration, not discovered during an incident.'],
    pmQuestions: ['What are the agreed RPO and RTO for this workload, and does the design actually meet them?'],
    relatedConcepts: ['rpo', 'rto', 'high-availability'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'rpo',
    name: 'Recovery Point Objective',
    acronym: 'RPO',
    domain: 'foundation',
    mapLayer: 'operations',
    purpose: 'The maximum acceptable amount of data loss, measured in time, after an incident.',
    definition: 'RPO defines how much data (measured as a period of time) the business can afford to lose in a disruption, which sets backup frequency requirements.',
    problemSolved: 'Turns a vague "don\'t lose data" goal into a measurable requirement that backup design must meet.',
    dependsOn: ['backup'],
    usedBy: [],
    projectRelevance: ['RPO is a business decision, not a technical one — the coordinator should confirm it is documented, not assumed.'],
    pmQuestions: ['Who set the RPO target, and does current backup frequency actually satisfy it?'],
    retrievalPrompt: 'How does RPO differ from RTO?',
    relatedConcepts: ['rto', 'backup', 'disaster-recovery'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'rto',
    name: 'Recovery Time Objective',
    acronym: 'RTO',
    domain: 'foundation',
    mapLayer: 'operations',
    purpose: 'The maximum acceptable time to restore a system after an incident.',
    definition: 'RTO defines how quickly a system must be restored after a disruption to meet business needs.',
    problemSolved: 'Turns "restore it fast" into a measurable target that recovery design and staffing must meet.',
    dependsOn: [],
    usedBy: [],
    projectRelevance: ['RTO drives decisions about redundancy, staffing during cutover, and whether a maintenance window is sufficient.'],
    pmQuestions: ['Does the planned maintenance window leave enough margin against the agreed RTO if something goes wrong?'],
    relatedConcepts: ['rpo', 'disaster-recovery'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },

  // ───────────────────────── CLOUD / AZ-900 ─────────────────────────
  {
    id: 'cloud-deployment-models',
    name: 'On-Premises, Cloud, and Hybrid',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'Describes where infrastructure and services physically and administratively live.',
    definition:
      'On-premises means infrastructure is owned and run in the organization\'s own facilities; cloud means it runs on a provider\'s infrastructure; hybrid combines both, often with integration between them.',
    problemSolved: 'Frames the starting point and target of a migration so scope and dependencies can be reasoned about.',
    dependsOn: [],
    usedBy: ['hybrid-identity'],
    projectRelevance: ['Current-state and target-state architecture diagrams should always specify which components are on-prem, cloud, or hybrid.'],
    pmQuestions: ['Which components are staying on-prem, and why?'],
    relatedConcepts: ['shared-responsibility', 'hybrid-identity'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'shared-responsibility',
    name: 'Shared Responsibility Model',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'Defines which security and management responsibilities belong to the cloud provider versus the customer.',
    definition: 'The shared responsibility model divides security and operational responsibilities between the cloud provider and the customer, and the split shifts depending on whether the service is IaaS, PaaS, or SaaS.',
    problemSolved: 'Prevents gaps where both sides assume the other is handling something (like patching or identity security).',
    dependsOn: [],
    usedBy: [],
    projectRelevance: ['Clarifying who owns which responsibility (patching, identity, data classification) should happen early in a project, not after an incident.'],
    pmQuestions: ['Has responsibility for security tasks been explicitly assigned, or just assumed?'],
    relatedConcepts: ['iaas-paas-saas', 'cloud-deployment-models'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'iaas-paas-saas',
    name: 'IaaS / PaaS / SaaS',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'Describes the three common cloud service models and how much a customer manages versus consumes.',
    definition:
      'IaaS (Infrastructure as a Service) provides raw compute/network/storage; PaaS (Platform as a Service) provides a managed platform to build on; SaaS (Software as a Service) delivers a ready-to-use application.',
    problemSolved: 'Clarifies how much operational overhead the organization retains versus hands to the provider.',
    dependsOn: [],
    usedBy: ['shared-responsibility'],
    projectRelevance: ['Service model choice affects who does patching, scaling, and configuration — directly shaping project workstreams.'],
    pmQuestions: ['For each in-scope workload, is it moving to IaaS, PaaS, or SaaS, and what does that change operationally?'],
    relatedConcepts: ['shared-responsibility'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'consumption-model',
    name: 'Consumption-Based Model',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'Describes paying for cloud resources based on actual use rather than upfront purchase.',
    definition: 'A consumption-based model charges for cloud resources based on measured usage rather than a fixed upfront purchase.',
    problemSolved: 'Conceptually shifts spend from capital investment to operating expense and lets cost scale with actual usage.',
    dependsOn: [],
    usedBy: ['cost-management'],
    projectRelevance: ['Cost visibility and governance become an ongoing project concern, not a one-time purchase decision. Exact pricing must always be verified against current Microsoft pricing pages.'],
    pmQuestions: ['Who owns ongoing cost monitoring after the project closes out?'],
    relatedConcepts: ['cost-management'],
    sourceIds: ['az900-cloud-concepts'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'azure-regions',
    name: 'Azure Regions and Availability Zones',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'Describes how Azure physically distributes infrastructure for resiliency and data locality.',
    definition: 'An Azure region is a geographic area containing datacenters; availability zones are physically separate locations within some regions used to increase resiliency.',
    problemSolved: 'Lets architects place workloads for resiliency, latency, and data residency requirements.',
    dependsOn: [],
    usedBy: ['high-availability'],
    projectRelevance: ['Region choice can affect data residency/compliance requirements that a project must confirm with the customer.'],
    pmQuestions: ['Are there data residency requirements that constrain which region can be used?'],
    relatedConcepts: ['high-availability'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'azure-tenant',
    name: 'Tenant',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'The dedicated instance of Microsoft Entra ID and associated services for an organization.',
    definition: 'A tenant is the dedicated, isolated instance of Microsoft Entra ID that represents an organization and holds its identities and directory data.',
    problemSolved: 'Provides an isolated administrative and identity boundary per organization.',
    dependsOn: ['entra-id'],
    usedBy: ['azure-subscription', 'm365-ecosystem'],
    projectRelevance: ['Tenant readiness (domain verification, initial configuration) is typically a prerequisite before licensing or pilot work can begin.'],
    pmQuestions: ['Is the tenant already provisioned and domain-verified, or does that need to happen first?'],
    relatedConcepts: ['entra-id', 'azure-subscription'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'management-group',
    name: 'Management Group',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'A container used to organize and apply governance across multiple Azure subscriptions.',
    definition: 'A management group is a scope above subscriptions used to apply policies and access controls consistently across many subscriptions.',
    problemSolved: 'Lets governance be applied once at a higher level instead of repeated per subscription.',
    dependsOn: ['azure-subscription'],
    usedBy: [],
    projectRelevance: ['Relevant mainly in larger or multi-subscription environments; small engagements may not need this layer.'],
    pmQuestions: ['Does this environment have enough subscriptions to warrant management group structure?'],
    relatedConcepts: ['azure-subscription', 'azure-policy'],
    sourceIds: ['az900-governance'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'azure-subscription',
    name: 'Subscription',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'The billing and access-control boundary for Azure resources.',
    definition: 'An Azure subscription is a logical container that groups resources for billing and access management, associated with a tenant.',
    problemSolved: 'Separates billing and access scopes, e.g., by department, environment, or project.',
    dependsOn: ['azure-tenant'],
    usedBy: ['resource-group'],
    projectRelevance: ['Subscription structure affects governance, cost tracking, and who can be granted access without over-provisioning.'],
    pmQuestions: ['Which subscription will this workload land in, and who owns its governance?'],
    relatedConcepts: ['resource-group', 'azure-tenant', 'rbac'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'resource-group',
    name: 'Resource Group',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'A logical container that groups related Azure resources for a solution.',
    definition: 'A resource group holds related Azure resources so they can be managed, deployed, and deleted together.',
    problemSolved: 'Simplifies lifecycle management by grouping resources that belong to the same solution.',
    dependsOn: ['azure-subscription'],
    usedBy: ['azure-resource'],
    projectRelevance: ['Resource group structure is often part of the design phase and should reflect how the workload will actually be managed.'],
    pmQuestions: ['Is there a naming and grouping convention agreed for this project?'],
    relatedConcepts: ['azure-subscription', 'azure-resource'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'azure-resource',
    name: 'Resource',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'A manageable item provisioned in Azure, such as a VM, storage account, or database.',
    definition: 'An Azure resource is an individual manageable entity such as a virtual machine, storage account, or web app, provisioned within a resource group.',
    problemSolved: 'The base unit of deployment and billing in Azure.',
    dependsOn: ['resource-group'],
    usedBy: [],
    projectRelevance: ['Resource inventory underpins discovery, cost estimation, and cutover planning.'],
    pmQuestions: ['Is there a current, accurate inventory of resources in scope?'],
    relatedConcepts: ['resource-group', 'compute', 'networking', 'storage'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'compute',
    name: 'Compute',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'Processing resources (VMs, containers, functions) that run workloads.',
    definition: 'Compute refers to the processing resources — virtual machines, containers, or serverless functions — that execute application workloads.',
    problemSolved: 'Provides the processing capacity applications and services run on.',
    dependsOn: ['azure-resource'],
    usedBy: ['application'],
    projectRelevance: ['Compute sizing and type (VM vs. PaaS vs. serverless) affects cost, migration complexity, and operational ownership.'],
    pmQuestions: ['Is the target compute model a lift-and-shift (VM) or a re-platform (PaaS/serverless)?'],
    relatedConcepts: ['iaas-paas-saas', 'networking', 'storage'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'networking',
    name: 'Azure Networking',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'The set of Azure services used to connect, isolate, and route traffic between resources.',
    definition: 'Azure networking includes virtual networks, subnets, routing, and connectivity services used to connect Azure resources to each other and to on-premises networks.',
    problemSolved: 'Provides connectivity and isolation for cloud resources, and a path to connect them to existing on-prem networks.',
    dependsOn: ['network'],
    usedBy: ['vnet'],
    projectRelevance: ['Network design is frequently on the critical path for hybrid connectivity work.'],
    pmQuestions: ['Is site-to-site or point-to-site connectivity required, and who owns the on-prem side?'],
    relatedConcepts: ['vnet', 'network'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'vnet',
    name: 'Virtual Network',
    acronym: 'VNet',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'An isolated network space in Azure for private communication between resources.',
    definition: 'A virtual network (VNet) is a logically isolated network in Azure used to securely connect Azure resources to each other, the internet, and on-premises networks.',
    problemSolved: 'Gives cloud resources a private, controllable network boundary similar to an on-prem LAN.',
    dependsOn: ['networking'],
    usedBy: ['compute'],
    projectRelevance: ['VNet address space must be planned to avoid overlap with on-prem ranges before hybrid connectivity is built.'],
    pmQuestions: ['Has IP address planning been done to avoid conflicts with on-prem networks?'],
    relatedConcepts: ['networking', 'ip-addressing'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'storage',
    name: 'Azure Storage',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'Cloud-based services for storing files, disks, and unstructured or structured data.',
    definition: 'Azure Storage provides durable, scalable cloud storage services for blobs, files, disks, and queues.',
    problemSolved: 'Provides persistent storage for compute workloads and data without managing physical hardware.',
    dependsOn: ['azure-resource'],
    usedBy: ['compute', 'backup'],
    projectRelevance: ['Storage tier and redundancy choices affect both cost and recovery posture — should be an explicit design decision.'],
    pmQuestions: ['What redundancy level does this data actually require?'],
    relatedConcepts: ['compute', 'backup'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'azure-database',
    name: 'Azure Databases',
    domain: 'cloud',
    mapLayer: 'azure',
    purpose: 'Managed database services offered on Azure.',
    definition: 'Azure offers managed database services (relational and non-relational) so organizations can run databases without managing the underlying infrastructure.',
    problemSolved: 'Reduces operational burden of patching and managing database servers directly.',
    dependsOn: ['azure-resource'],
    usedBy: ['application'],
    projectRelevance: ['Moving from a self-managed database to a managed Azure database is a re-platform, not a simple lift-and-shift, and needs compatibility testing.'],
    pmQuestions: ['Has compatibility testing been scheduled before cutover, not just after?'],
    relatedConcepts: ['database', 'application'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'rbac',
    name: 'Role-Based Access Control',
    acronym: 'RBAC',
    domain: 'cloud',
    mapLayer: 'identity',
    purpose: 'Grants access based on a user\'s assigned role rather than individually per resource.',
    definition: 'RBAC assigns permissions to roles, and roles to users or groups, so access is managed consistently instead of one-off per resource.',
    problemSolved: 'Reduces both over-provisioned access and administrative overhead compared to assigning permissions individually.',
    dependsOn: ['authorization'],
    usedBy: [],
    projectRelevance: ['Role design and assignment reviews are common project deliverables during identity or governance workstreams.'],
    pmQuestions: ['Who is accountable for reviewing and approving role assignments?'],
    relatedConcepts: ['authorization', 'least-privilege', 'azure-policy'],
    sourceIds: ['az900-governance'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'azure-policy',
    name: 'Azure Policy',
    domain: 'cloud',
    mapLayer: 'security',
    purpose: 'Enforces organizational rules and standards across Azure resources.',
    definition: 'Azure Policy evaluates resources against defined rules and can audit or enforce compliance with those rules.',
    problemSolved: 'Keeps environments consistent with governance standards without manual, resource-by-resource review.',
    dependsOn: ['management-group'],
    usedBy: [],
    projectRelevance: ['Policy definitions can block or flag non-compliant deployments — should be understood before a migration runs into unexpected denials.'],
    pmQuestions: ['Are there existing policies that could block this deployment, and has that been checked?'],
    relatedConcepts: ['rbac', 'resource-locks'],
    sourceIds: ['az900-governance'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'resource-locks',
    name: 'Resource Locks',
    domain: 'cloud',
    mapLayer: 'security',
    purpose: 'Prevents accidental deletion or modification of critical Azure resources.',
    definition: 'A resource lock is a setting applied to an Azure resource that prevents it from being deleted or modified, even by users with sufficient permissions.',
    problemSolved: 'Guards against accidental changes to critical infrastructure.',
    dependsOn: [],
    usedBy: [],
    projectRelevance: ['Locks can unexpectedly block a planned change during cutover if not accounted for in the runbook.'],
    pmQuestions: ['Are any in-scope resources locked, and who can remove the lock if needed?'],
    relatedConcepts: ['azure-policy'],
    sourceIds: ['az900-governance'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'azure-monitor',
    name: 'Azure Monitor',
    domain: 'cloud',
    mapLayer: 'operations',
    purpose: 'Collects and analyzes telemetry from Azure resources for visibility and alerting.',
    definition: 'Azure Monitor collects metrics and logs from Azure resources and can be used to visualize health and trigger alerts.',
    problemSolved: 'Gives operations visibility into resource health instead of relying on user-reported issues.',
    dependsOn: ['logs'],
    usedBy: ['service-health'],
    projectRelevance: ['Monitoring/alerting setup is a common hypercare and operational-handoff deliverable.'],
    pmQuestions: ['Who owns alerting after the project moves into hypercare and closeout?'],
    relatedConcepts: ['logs', 'service-health'],
    sourceIds: ['az900-governance'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'cost-management',
    name: 'Cost Management',
    domain: 'cloud',
    mapLayer: 'operations',
    purpose: 'Tools and practices for tracking and controlling cloud spend.',
    definition: 'Azure Cost Management provides visibility into spend and tools to set budgets and alerts against consumption-based billing.',
    problemSolved: 'Prevents unexpected spend by making usage and cost visible on an ongoing basis.',
    dependsOn: ['consumption-model'],
    usedBy: [],
    projectRelevance: ['Cost ownership after go-live should be assigned explicitly — it is easy for this to fall through the cracks after project closeout.'],
    pmQuestions: ['Who reviews the cost dashboard after this project closes?'],
    relatedConcepts: ['consumption-model'],
    sourceIds: ['az900-governance'],
    verificationDate: '2026-09-01',
  },

  // ───────────────────────── MICROSOFT 365 ─────────────────────────
  {
    id: 'm365-ecosystem',
    name: 'Microsoft 365',
    acronym: 'M365',
    domain: 'm365',
    mapLayer: 'workloads',
    purpose: 'Microsoft\'s suite of cloud productivity, collaboration, and device management services.',
    definition: 'Microsoft 365 is a subscription bundle of productivity and collaboration services (Exchange Online, Teams, SharePoint, OneDrive, and more) built on a shared tenant and identity foundation.',
    problemSolved: 'Provides an integrated set of business productivity services rather than disconnected point tools.',
    dependsOn: ['azure-tenant', 'entra-id'],
    usedBy: ['exchange-online', 'teams', 'sharepoint-online', 'onedrive'],
    projectRelevance: ['Most Microsoft 365 projects involve some combination of licensing, identity readiness, and workload-specific configuration.'],
    pmQuestions: ['Which specific M365 workloads are actually in scope for this project?'],
    relatedConcepts: ['exchange-online', 'teams', 'sharepoint-online', 'entra-id'],
    sourceIds: ['ab900-what-is-m365', 'm365-admin-path'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'exchange-online',
    name: 'Exchange Online',
    domain: 'm365',
    mapLayer: 'workloads',
    purpose: 'Microsoft 365\'s cloud-hosted email and calendaring service.',
    definition: 'Exchange Online is the cloud-hosted email, calendar, and contacts service within Microsoft 365.',
    problemSolved: 'Removes the need to operate on-premises mail servers directly.',
    dependsOn: ['m365-ecosystem', 'dns'],
    usedBy: [],
    projectRelevance: ['Mail migration projects require DNS coordination, licensing assignment, and a pilot mailbox cohort before broad cutover.'],
    pmQuestions: ['Has a pilot mailbox cohort been identified before the full migration wave?'],
    relatedConcepts: ['dns', 'm365-ecosystem'],
    sourceIds: ['ab900-what-is-m365'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    domain: 'm365',
    mapLayer: 'workloads',
    purpose: 'Microsoft 365\'s chat, meetings, and collaboration hub.',
    definition: 'Microsoft Teams is a collaboration workload for chat, meetings, and calling, integrated with other Microsoft 365 services such as SharePoint.',
    problemSolved: 'Centralizes team communication and collaboration in one connected workspace.',
    dependsOn: ['m365-ecosystem'],
    usedBy: [],
    projectRelevance: ['Teams rollout often needs user training and governance decisions (team creation, naming, guest access) as part of scope.'],
    pmQuestions: ['Who owns governance decisions like team creation policy and guest access?'],
    relatedConcepts: ['sharepoint-online', 'm365-ecosystem'],
    sourceIds: ['ab900-what-is-m365'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'sharepoint-online',
    name: 'SharePoint Online',
    domain: 'm365',
    mapLayer: 'workloads',
    purpose: 'Microsoft 365\'s service for team sites, document libraries, and content collaboration.',
    definition: 'SharePoint Online provides team and communication sites, document libraries, and content collaboration within Microsoft 365.',
    problemSolved: 'Provides structured, permissioned content storage and collaboration beyond individual file shares.',
    dependsOn: ['m365-ecosystem'],
    usedBy: ['teams'],
    projectRelevance: ['File share migrations to SharePoint often surface permission and folder-structure decisions that need customer input.'],
    pmQuestions: ['Is the existing permission structure being replicated as-is, or redesigned during migration?'],
    relatedConcepts: ['onedrive', 'teams'],
    sourceIds: ['ab900-what-is-m365'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    domain: 'm365',
    mapLayer: 'workloads',
    purpose: 'Microsoft 365\'s personal cloud storage and file sync service.',
    definition: 'OneDrive provides personal cloud file storage and sync for individual users within Microsoft 365.',
    problemSolved: 'Gives each user personal cloud storage, distinct from shared SharePoint site storage.',
    dependsOn: ['m365-ecosystem'],
    usedBy: [],
    projectRelevance: ['Distinguishing OneDrive (personal) from SharePoint (shared/team) matters when scoping a file migration.'],
    pmQuestions: ['Is content being migrated to personal OneDrive, shared SharePoint, or both?'],
    retrievalPrompt: 'What is the key difference between OneDrive and SharePoint Online?',
    relatedConcepts: ['sharepoint-online'],
    sourceIds: ['ab900-what-is-m365'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'm365-apps',
    name: 'Microsoft 365 Apps',
    domain: 'm365',
    mapLayer: 'endpoint',
    purpose: 'The installable Office desktop and mobile applications included with many Microsoft 365 plans.',
    definition: 'Microsoft 365 Apps refers to the installable desktop and mobile applications (Word, Excel, Outlook, and others) that can be deployed as part of a Microsoft 365 subscription.',
    problemSolved: 'Delivers familiar productivity applications alongside the cloud services.',
    dependsOn: ['m365-ecosystem'],
    usedBy: [],
    projectRelevance: ['App deployment method (Intune, manual, other) is a decision point during endpoint readiness planning.'],
    pmQuestions: ['How will these apps be deployed to endpoints — centrally managed or self-installed?'],
    relatedConcepts: ['intune', 'm365-ecosystem'],
    sourceIds: ['ab900-what-is-m365'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'm365-admin-center',
    name: 'Microsoft 365 Admin Center',
    domain: 'm365',
    mapLayer: 'operations',
    purpose: 'The central console for managing users, licenses, and settings across Microsoft 365.',
    definition: 'The Microsoft 365 admin center is the primary web console for managing users, groups, licenses, and tenant-wide settings, with links out to specialized admin centers per workload.',
    problemSolved: 'Provides one starting point for tenant administration instead of scattered per-service consoles.',
    dependsOn: ['m365-ecosystem'],
    usedBy: [],
    projectRelevance: ['Delegated admin roles here determine who on the project team can actually make changes.'],
    pmQuestions: ['Who has been granted admin access, and is it scoped appropriately (least privilege)?'],
    relatedConcepts: ['rbac', 'service-health'],
    sourceIds: ['m365-admin-path'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'service-health',
    name: 'Service Health',
    domain: 'm365',
    mapLayer: 'operations',
    purpose: 'The dashboard reporting current incidents and planned maintenance for Microsoft 365 services.',
    definition: 'Service Health is a Microsoft 365 admin center feature reporting active incidents, advisories, and planned maintenance for the tenant\'s services.',
    problemSolved: 'Gives administrators visibility into whether an issue is tenant-specific or a broader Microsoft service event.',
    dependsOn: ['m365-admin-center'],
    usedBy: [],
    projectRelevance: ['Checking service health should be a standard step before escalating a cutover issue as a project defect.'],
    pmQuestions: ['Has service health been checked before treating this as a project-caused issue?'],
    relatedConcepts: ['m365-admin-center', 'azure-monitor'],
    sourceIds: ['m365-admin-path'],
    verificationDate: '2026-09-01',
  },

  {
    id: 'power-platform',
    name: 'Power Platform',
    domain: 'm365',
    mapLayer: 'workloads',
    purpose: 'Microsoft\'s low-code suite for building apps, automating workflows, and analyzing data.',
    definition: 'Power Platform is Microsoft\'s low-code suite, including Power Apps (app building), Power Automate (workflow automation), Power BI (analytics), and Power Virtual Agents (chatbots), typically built on top of the Microsoft 365 and Azure identity foundation.',
    problemSolved: 'Lets business users and IT build lightweight apps and automations without full custom software development.',
    dependsOn: ['entra-id'],
    usedBy: [],
    projectRelevance: ['Custom Power Platform apps/flows are often an overlooked dependency discovered late in a migration if not inventoried during discovery.'],
    pmQuestions: ['Are there existing Power Platform apps or flows that depend on systems being migrated?'],
    relatedConcepts: ['m365-ecosystem', 'entra-id'],
    sourceIds: ['ab900-what-is-m365'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'data-analytics-workloads',
    name: 'Data / Analytics Workloads',
    domain: 'cloud',
    mapLayer: 'workloads',
    purpose: 'Services used to store, process, and visualize business data.',
    definition: 'Data and analytics workloads (such as Power BI for visualization, and Azure data services for storage and processing) turn raw data into reporting and insight.',
    problemSolved: 'Gives the business visibility into its own data instead of leaving it siloed and unexamined.',
    dependsOn: [],
    usedBy: [],
    projectRelevance: ['Reporting and analytics dependencies on a data source should be identified before that source is migrated or decommissioned.'],
    pmQuestions: ['Does any reporting or analytics tool depend on the system being migrated?'],
    relatedConcepts: ['azure-database', 'storage'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },

  // ───────────────────────── IDENTITY ─────────────────────────
  {
    id: 'ad-ds',
    name: 'Active Directory Domain Services',
    acronym: 'AD DS',
    domain: 'identity',
    mapLayer: 'identity',
    purpose: 'The traditional on-premises Microsoft directory service for authentication and authorization.',
    definition: 'AD DS is Microsoft\'s on-premises directory service that stores identity objects and provides authentication and authorization within a Windows domain.',
    problemSolved: 'Provides centralized on-premises identity management and single sign-on within a corporate network.',
    dependsOn: ['directory-services'],
    usedBy: ['hybrid-identity'],
    projectRelevance: ['Whether AD DS remains authoritative, is retired, or is synchronized to the cloud is a foundational identity decision for any migration.'],
    pmQuestions: ['Will AD DS remain authoritative for identity, or is the organization moving fully to cloud identity?'],
    retrievalPrompt: 'How is AD DS different from Entra ID?',
    relatedConcepts: ['entra-id', 'hybrid-identity', 'entra-connect'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'entra-id',
    name: 'Microsoft Entra ID',
    aliases: ['Azure Active Directory', 'Azure AD'],
    domain: 'identity',
    mapLayer: 'identity',
    purpose: 'Microsoft\'s cloud-based identity and access management service.',
    definition: 'Microsoft Entra ID is Microsoft\'s cloud identity and access management service, used for authentication and authorization across Microsoft 365, Azure, and integrated applications. It was previously named Azure Active Directory (Azure AD).',
    problemSolved: 'Provides cloud-based identity so users can authenticate to Microsoft 365, Azure, and other integrated apps from anywhere.',
    dependsOn: ['directory-services'],
    usedBy: ['m365-ecosystem', 'azure-tenant', 'conditional-access', 'mfa', 'sso'],
    projectRelevance: ['Entra ID is the identity foundation nearly every Microsoft 365 and Azure project depends on — tenant readiness usually starts here.'],
    pmQuestions: ['Is the tenant\'s Entra ID configuration (domains, sync, security defaults) already validated for this project?'],
    commonTerms: ['tenant', 'directory', 'identity provider'],
    relatedConcepts: ['ad-ds', 'hybrid-identity', 'conditional-access', 'azure-tenant'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'hybrid-identity',
    name: 'Hybrid Identity',
    domain: 'identity',
    mapLayer: 'identity',
    purpose: 'An identity model where on-premises AD DS and cloud Entra ID are integrated and kept in sync.',
    definition: 'Hybrid identity is an architecture where on-premises Active Directory and Microsoft Entra ID are integrated, typically via directory synchronization, so users have a consistent identity across both environments.',
    problemSolved: 'Lets organizations keep an existing on-prem directory as a source while enabling cloud service access, instead of maintaining two disconnected identity stores.',
    dependsOn: ['ad-ds', 'entra-id'],
    usedBy: [],
    projectRelevance: ['This is the identity pattern in the example scenario: "The customer is running hybrid identity, Entra Connect is synchronizing users."'],
    pmQuestions: ['What is being synchronized (users, groups, devices), and how often does sync run?'],
    relatedConcepts: ['entra-connect', 'ad-ds', 'entra-id'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'entra-connect',
    name: 'Microsoft Entra Connect (Sync)',
    domain: 'identity',
    mapLayer: 'identity',
    purpose: 'The Microsoft tool that synchronizes on-premises AD DS identities to Microsoft Entra ID.',
    definition: 'Microsoft Entra Connect is the Microsoft tool used to synchronize identity objects and attributes from on-premises Active Directory to Microsoft Entra ID to support hybrid identity.',
    problemSolved: 'Keeps cloud identity consistent with the on-premises directory without manual duplication of accounts.',
    dependsOn: ['ad-ds', 'entra-id'],
    usedBy: ['hybrid-identity'],
    projectRelevance: ['Sync health and schedule should be confirmed before any migration wave that depends on accurate, current identity data.'],
    pmQuestions: ['When did sync last run successfully, and who monitors sync health?'],
    relatedConcepts: ['hybrid-identity', 'ad-ds', 'entra-id'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'mfa',
    name: 'Multi-Factor Authentication',
    acronym: 'MFA',
    domain: 'identity',
    mapLayer: 'identity',
    purpose: 'Requires more than one form of verification to authenticate.',
    definition: 'Multi-factor authentication requires a user to present two or more independent forms of verification (something they know, have, or are) to authenticate.',
    problemSolved: 'Reduces the risk of account compromise from a single stolen credential like a password.',
    dependsOn: ['authentication'],
    usedBy: ['conditional-access'],
    projectRelevance: ['MFA rollouts need exclusion/exception handling, a pilot group, and support readiness before broad enforcement.'],
    pmQuestions: ['Is there a defined exception process for accounts that cannot immediately use MFA (e.g., service accounts)?'],
    relatedConcepts: ['conditional-access', 'authentication'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'sso',
    name: 'Single Sign-On',
    acronym: 'SSO',
    domain: 'identity',
    mapLayer: 'identity',
    purpose: 'Lets a user authenticate once and access multiple connected applications without re-entering credentials.',
    definition: 'Single sign-on lets a user authenticate once with an identity provider and gain access to multiple integrated applications without signing in again to each one.',
    problemSolved: 'Reduces password fatigue and repeated logins across integrated applications.',
    dependsOn: ['authentication'],
    usedBy: [],
    projectRelevance: ['Application onboarding to SSO is a common project workstream when consolidating identity onto Entra ID.'],
    pmQuestions: ['Which applications are being integrated with SSO in this phase, and which are deferred?'],
    relatedConcepts: ['authentication', 'entra-id'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'conditional-access',
    name: 'Conditional Access',
    domain: 'identity',
    mapLayer: 'identity',
    purpose: 'A policy engine that grants or blocks access based on defined conditions such as user, location, device, and risk.',
    definition: 'Conditional Access is a Microsoft Entra ID feature that evaluates signals (user, location, device state, sign-in risk) and enforces access controls such as requiring MFA or blocking access when policy conditions are met.',
    problemSolved: 'Applies access decisions based on context and risk instead of a single static allow/deny rule.',
    dependsOn: ['entra-id', 'mfa'],
    usedBy: [],
    projectRelevance: ['Conditional Access changes affect user access immediately, so they need a pilot group, exception handling, and clear rollback before broad enforcement.'],
    pmQuestions: [
      'What must be clarified before broad Conditional Access enforcement — pilot scope, break-glass accounts, and legacy app exceptions?',
      'Is there a break-glass (emergency access) account excluded from policy in case of lockout?',
    ],
    analogy: 'Less like a locked door and more like an access-control point that checks multiple conditions before granting entry.',
    analogyLabel: 'Conceptual analogy, not a technical definition',
    retrievalPrompt: 'What must a coordinator clarify before broad Conditional Access enforcement?',
    relatedConcepts: ['mfa', 'entra-id', 'intune'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'least-privilege',
    name: 'Least Privilege',
    domain: 'identity',
    mapLayer: 'identity',
    purpose: 'A security principle of granting only the access necessary to perform a task.',
    definition: 'Least privilege is the practice of granting a user or system only the minimum access needed to do its job, and no more.',
    problemSolved: 'Limits the damage a compromised account or process can cause.',
    dependsOn: ['authorization'],
    usedBy: [],
    projectRelevance: ['Access reviews conducted during a project are a chance to correct over-provisioned access, not just replicate it.'],
    pmQuestions: ['Is this project replicating existing access as-is, or taking the opportunity to right-size it?'],
    relatedConcepts: ['rbac', 'authorization'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },

  // ───────────────────────── ENDPOINT MANAGEMENT ─────────────────────────
  {
    id: 'intune',
    name: 'Microsoft Intune',
    domain: 'endpoint',
    mapLayer: 'endpoint',
    purpose: 'Microsoft\'s cloud-based endpoint management service for devices and apps.',
    definition: 'Microsoft Intune is a cloud-based service for managing devices and applications, supporting both device management (MDM) and app-level management (MAM), and integrating with Conditional Access for compliance-based access control.',
    problemSolved: 'Lets organizations enroll, configure, secure, and manage devices without on-premises management infrastructure.',
    dependsOn: ['endpoint-device'],
    usedBy: ['compliance-policy', 'conditional-access'],
    projectRelevance: ['Intune rollout is a frequent prerequisite before an organization can safely enforce device-based Conditional Access.'],
    pmQuestions: ['Is device compliance already established, or does it need to reach a defined threshold before access enforcement begins?'],
    relatedConcepts: ['mdm', 'mam', 'compliance-policy', 'conditional-access'],
    sourceIds: ['m365-admin-path'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'mdm',
    name: 'Mobile Device Management',
    acronym: 'MDM',
    domain: 'endpoint',
    mapLayer: 'endpoint',
    purpose: 'Management of an entire device, including configuration, compliance, and remote actions like wipe.',
    definition: 'MDM manages an entire enrolled device — settings, compliance, and remote actions such as wipe — typically for corporate-owned devices.',
    problemSolved: 'Gives IT full management control over corporate devices.',
    dependsOn: ['intune'],
    usedBy: [],
    projectRelevance: ['MDM enrollment approach (corporate-owned) differs from MAM (BYOD) and should be scoped explicitly per device ownership type.'],
    pmQuestions: ['Which device ownership categories require full MDM versus lighter MAM management?'],
    retrievalPrompt: 'How does MDM differ from MAM?',
    relatedConcepts: ['mam', 'intune', 'enrollment'],
    sourceIds: ['m365-admin-path'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'mam',
    name: 'Mobile Application Management',
    acronym: 'MAM',
    domain: 'endpoint',
    mapLayer: 'endpoint',
    purpose: 'Management scoped to specific applications and their data, without managing the whole device.',
    definition: 'MAM manages and protects specific applications and their data (e.g., Outlook, Teams) on a device without taking control of the entire device — common for personal (BYOD) devices.',
    problemSolved: 'Protects corporate data on personal devices without requiring full device control, which users are often unwilling to grant.',
    dependsOn: ['intune'],
    usedBy: [],
    projectRelevance: ['BYOD scope should specify MAM policy requirements separately from corporate-device MDM requirements.'],
    pmQuestions: ['Are BYOD devices in scope, and if so, what MAM policies apply to them?'],
    relatedConcepts: ['mdm', 'intune'],
    sourceIds: ['m365-admin-path'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'enrollment',
    name: 'Device Enrollment',
    domain: 'endpoint',
    mapLayer: 'endpoint',
    purpose: 'The process of registering a device with Intune so it can be managed.',
    definition: 'Enrollment is the process by which a device is registered with an endpoint management service so it can receive policy, configuration, and compliance evaluation.',
    problemSolved: 'Establishes the managed relationship between the device and Intune before any policy can apply.',
    dependsOn: ['intune'],
    usedBy: [],
    projectRelevance: ['Enrollment method (manual, Autopilot, co-management) affects rollout pacing and support burden.'],
    pmQuestions: ['What enrollment method is planned, and what is the estimated support load per device?'],
    relatedConcepts: ['autopilot', 'intune'],
    sourceIds: ['m365-admin-path'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'compliance-policy',
    name: 'Compliance Policy',
    domain: 'endpoint',
    mapLayer: 'endpoint',
    purpose: 'Rules that define whether a device meets required security and configuration standards.',
    definition: 'A compliance policy in Intune defines the conditions a device must meet (e.g., encryption enabled, OS version, password requirement) to be marked compliant.',
    problemSolved: 'Gives Conditional Access a measurable device-state signal to make access decisions against.',
    dependsOn: ['intune', 'endpoint-device'],
    usedBy: ['conditional-access'],
    projectRelevance: ['Compliance thresholds should be reached and validated before they are used to gate access, to avoid locking out legitimate users.'],
    pmQuestions: ['What percentage of devices are currently compliant, and is that acceptable before enforcement begins?'],
    relatedConcepts: ['conditional-access', 'intune'],
    sourceIds: ['m365-admin-path'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'configuration-profiles',
    name: 'Configuration Profiles',
    domain: 'endpoint',
    mapLayer: 'endpoint',
    purpose: 'Settings pushed to devices to configure them consistently.',
    definition: 'Configuration profiles are sets of settings deployed through Intune to configure device behavior consistently across a fleet.',
    problemSolved: 'Standardizes device configuration instead of relying on manual per-device setup.',
    dependsOn: ['intune'],
    usedBy: [],
    projectRelevance: ['Profile design should be validated in pilot before broad deployment to avoid fleet-wide misconfiguration.'],
    pmQuestions: ['Has this configuration been validated on a pilot device group first?'],
    relatedConcepts: ['intune', 'compliance-policy'],
    sourceIds: ['m365-admin-path'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'autopilot',
    name: 'Windows Autopilot',
    domain: 'endpoint',
    mapLayer: 'endpoint',
    purpose: 'A Microsoft service for pre-configuring and provisioning new Windows devices out of the box.',
    definition: 'Windows Autopilot is a Microsoft service used to pre-register and automatically configure new Windows devices so they are ready to use with minimal manual IT setup.',
    problemSolved: 'Reduces manual imaging effort by letting a device configure itself from the cloud on first boot.',
    dependsOn: ['intune'],
    usedBy: ['enrollment'],
    projectRelevance: ['Autopilot requires device hardware IDs registered ahead of rollout — a common overlooked prerequisite in device refresh projects.'],
    pmQuestions: ['Have device hardware IDs been collected and registered before the rollout date?'],
    relatedConcepts: ['enrollment', 'intune'],
    sourceIds: ['m365-admin-path'],
    verificationDate: '2026-09-01',
  },

  // ───────────────────────── SECURITY ─────────────────────────
  {
    id: 'zero-trust',
    name: 'Zero Trust',
    domain: 'security',
    mapLayer: 'security',
    purpose: 'A security model that assumes no user or device is trusted by default, even inside the network perimeter.',
    definition: 'Zero Trust is a security model built on explicitly verifying every access request, using least-privilege access, and assuming breach rather than trusting anything by default based on network location.',
    problemSolved: 'Addresses the weakness of perimeter-based trust, where anything inside the network was historically assumed safe.',
    dependsOn: [],
    usedBy: ['conditional-access'],
    projectRelevance: ['Zero Trust is often the stated rationale behind identity and access hardening projects — useful context for why a customer wants MFA/Conditional Access work.'],
    pmQuestions: ['Is this project part of a broader stated Zero Trust initiative, or a standalone control?'],
    relatedConcepts: ['conditional-access', 'least-privilege'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'defender-family',
    name: 'Microsoft Defender (product family)',
    domain: 'security',
    mapLayer: 'security',
    purpose: 'Microsoft\'s family of security products covering endpoints, email, cloud, and identity threats.',
    definition: 'Microsoft Defender is a family of security products, including endpoint, email, and cloud-focused offerings, unified for threat protection across a Microsoft environment.',
    problemSolved: 'Provides connected threat detection and response across multiple attack surfaces instead of disconnected point tools.',
    dependsOn: [],
    usedBy: ['defender-endpoint', 'defender-office', 'defender-cloud'],
    projectRelevance: ['Understanding which Defender products are licensed and enabled clarifies what security capability the customer already has.'],
    pmQuestions: ['Which Defender products are currently licensed and actively configured, versus just licensed but unused?'],
    relatedConcepts: ['defender-endpoint', 'defender-office', 'defender-cloud', 'sentinel'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'defender-endpoint',
    name: 'Microsoft Defender for Endpoint',
    domain: 'security',
    mapLayer: 'security',
    purpose: 'Endpoint detection and response for devices.',
    definition: 'Microsoft Defender for Endpoint provides endpoint protection, detection, and response capabilities for managed devices.',
    problemSolved: 'Detects and helps respond to threats on endpoints, complementing endpoint management.',
    dependsOn: ['defender-family', 'endpoint-device'],
    usedBy: [],
    projectRelevance: ['Endpoint security posture often ties into the same endpoint readiness work as Intune enrollment.'],
    pmQuestions: ['Is endpoint security onboarding part of this project or a separate initiative?'],
    relatedConcepts: ['defender-family', 'intune'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'defender-office',
    name: 'Microsoft Defender for Office 365',
    domain: 'security',
    mapLayer: 'security',
    purpose: 'Protection against email and collaboration threats such as phishing and malicious links.',
    definition: 'Microsoft Defender for Office 365 provides protection against phishing, malware, and malicious links/attachments within Exchange Online and other Microsoft 365 collaboration tools.',
    problemSolved: 'Adds threat protection layers on top of baseline Exchange Online mail flow.',
    dependsOn: ['defender-family', 'exchange-online'],
    usedBy: [],
    projectRelevance: ['Mail migration projects should confirm whether Defender for Office 365 protections are configured before go-live, not after.'],
    pmQuestions: ['Are anti-phishing and safe-links policies configured before mailboxes go live?'],
    relatedConcepts: ['defender-family', 'exchange-online'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'defender-cloud',
    name: 'Microsoft Defender for Cloud',
    domain: 'security',
    mapLayer: 'security',
    purpose: 'Security posture management and threat protection for cloud and hybrid workloads.',
    definition: 'Microsoft Defender for Cloud provides security posture recommendations and threat protection for Azure and hybrid resources.',
    problemSolved: 'Surfaces misconfigurations and threats in cloud infrastructure that would otherwise go unnoticed.',
    dependsOn: ['defender-family'],
    usedBy: [],
    projectRelevance: ['Recommendations here can inform the acceptance criteria for a completed Azure migration.'],
    pmQuestions: ['Will Defender for Cloud recommendations be reviewed as part of go-live acceptance?'],
    relatedConcepts: ['defender-family', 'azure-policy'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'sentinel',
    name: 'Microsoft Sentinel',
    domain: 'security',
    mapLayer: 'security',
    purpose: 'Microsoft\'s cloud-native SIEM and SOAR service for security monitoring and response.',
    definition: 'Microsoft Sentinel is a cloud-native SIEM (security information and event management) and SOAR (security orchestration, automation, and response) service used to collect, detect, investigate, and respond to security threats across an environment.',
    problemSolved: 'Aggregates security signal from many sources into one place for detection and investigation.',
    dependsOn: ['logs'],
    usedBy: [],
    projectRelevance: ['A new Sentinel deployment or expanded data connectors is itself a project with onboarding and tuning phases.'],
    pmQuestions: ['Which log sources are being onboarded to Sentinel in this phase?'],
    relatedConcepts: ['siem', 'defender-family'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'siem',
    name: 'SIEM / SOC',
    acronym: 'SIEM',
    domain: 'security',
    mapLayer: 'security',
    purpose: 'The tooling (SIEM) and team (SOC) responsible for collecting security signal and responding to incidents.',
    definition: 'A SIEM (security information and event management) system aggregates and correlates security signals; a SOC (security operations center) is the team that monitors and responds to what the SIEM surfaces.',
    problemSolved: 'Provides the centralized detection and human response process an organization needs to act on security events.',
    dependsOn: [],
    usedBy: [],
    projectRelevance: ['Understanding whether a SOC exists, and whose SOC it is (internal or MSP), matters for incident-driven projects.'],
    pmQuestions: ['Is there an internal SOC, an outsourced SOC, or none, and how does that affect this project\'s escalation path?'],
    relatedConcepts: ['sentinel', 'defender-family'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'purview',
    name: 'Microsoft Purview',
    domain: 'security',
    mapLayer: 'security',
    purpose: 'Microsoft\'s data governance, compliance, and information protection platform.',
    definition: 'Microsoft Purview provides data governance, compliance, and information protection capabilities, such as data classification, retention, and data loss prevention, across Microsoft 365 and beyond.',
    problemSolved: 'Helps organizations understand, classify, and govern data to meet compliance and data protection needs.',
    dependsOn: [],
    usedBy: [],
    projectRelevance: ['Retention and data loss prevention policy decisions in Purview can affect what a migration is allowed to move or delete.'],
    pmQuestions: ['Are there existing retention or DLP policies that constrain what this migration can touch?'],
    relatedConcepts: ['m365-ecosystem'],
    sourceIds: ['sc900-cert'],
    verificationDate: '2026-09-01',
  },

  // ───────────────────────── MIGRATION DELIVERY ─────────────────────────
  {
    id: 'discover-phase',
    name: 'Discovery',
    domain: 'migration',
    mapLayer: 'operations',
    purpose: 'The phase of identifying what currently exists before planning a change.',
    definition: 'Discovery is the phase of identifying current-state systems, dependencies, and constraints before design work begins.',
    problemSolved: 'Surfaces unknowns (like undocumented application dependencies) before they become migration-day surprises.',
    dependsOn: [],
    usedBy: ['assess-phase'],
    projectRelevance: ['Skipping or rushing discovery is one of the most common causes of migration rework.'],
    pmQuestions: ['What discovery has actually been completed and documented, versus assumed?'],
    relatedConcepts: ['assess-phase', 'application'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'assess-phase',
    name: 'Assess',
    domain: 'migration',
    mapLayer: 'operations',
    purpose: 'Evaluating discovered systems against the target architecture to identify gaps and risks.',
    definition: 'Assessment evaluates discovered systems and dependencies against the intended target state to identify gaps, risks, and readiness.',
    problemSolved: 'Turns raw discovery data into an informed judgment about what is ready to migrate and what needs remediation first.',
    dependsOn: ['discover-phase'],
    usedBy: ['design-phase'],
    projectRelevance: ['Assessment findings should directly shape the project plan, not be filed away after the workshop.'],
    pmQuestions: ['Have assessment findings been translated into scoped action items with owners?'],
    relatedConcepts: ['discover-phase', 'design-phase'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'design-phase',
    name: 'Design',
    domain: 'migration',
    mapLayer: 'operations',
    purpose: 'Defining the target architecture and migration approach based on assessment findings.',
    definition: 'Design is the phase where the target architecture, sequencing, and migration approach are defined based on discovery and assessment.',
    problemSolved: 'Produces an agreed technical plan before implementation work starts.',
    dependsOn: ['assess-phase'],
    usedBy: ['pilot-phase'],
    projectRelevance: ['The design should be reviewed and formally accepted before build work begins, to avoid rework from late-stage design changes.'],
    pmQuestions: ['Has the customer formally accepted the design, or is it still under review?'],
    relatedConcepts: ['assess-phase', 'pilot-phase'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'pilot-phase',
    name: 'Pilot',
    domain: 'migration',
    mapLayer: 'operations',
    purpose: 'A small-scale rollout used to validate an approach before broad deployment.',
    definition: 'A pilot is a small, representative rollout used to validate the migration or deployment approach before it is applied broadly.',
    problemSolved: 'Surfaces issues on a small, controlled group instead of the entire user population.',
    dependsOn: ['design-phase'],
    usedBy: ['cutover'],
    projectRelevance: ['A pilot cohort should be representative (including edge cases like executives or specialized roles), not just the easiest users to migrate.'],
    pmQuestions: ['Does the pilot group represent the range of real usage patterns, including edge cases?'],
    relatedConcepts: ['design-phase', 'cutover'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'cutover',
    name: 'Cutover',
    domain: 'migration',
    mapLayer: 'operations',
    purpose: 'The point at which users or systems switch from the old environment to the new one.',
    definition: 'Cutover is the planned switch from the old system or state to the new one, typically executed against a defined runbook within a maintenance window.',
    problemSolved: 'Coordinates a controlled transition instead of an ad hoc switch, reducing the chance of avoidable disruption.',
    dependsOn: ['pilot-phase', 'maintenance-window'],
    usedBy: ['validate-phase'],
    projectRelevance: ['Cutover should always have a written runbook with sequencing, owners, validation steps, and a rollback plan.'],
    pmQuestions: ['Is there a written cutover runbook with a rollback plan, or is this being run informally?'],
    relatedConcepts: ['maintenance-window', 'rollback', 'validate-phase'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'validate-phase',
    name: 'Validate',
    domain: 'migration',
    mapLayer: 'operations',
    purpose: 'Confirming the migrated system works correctly before declaring cutover complete.',
    definition: 'Validation is the step of confirming, against defined criteria, that a migrated system or change works correctly before it is accepted as complete.',
    problemSolved: 'Prevents declaring success before the change has actually been confirmed to work.',
    dependsOn: ['cutover'],
    usedBy: ['acceptance-criteria'],
    projectRelevance: ['Validation steps should be defined and agreed before cutover starts, not improvised afterward.'],
    pmQuestions: ['What specific checks constitute a successful validation, and who signs off on them?'],
    relatedConcepts: ['acceptance-criteria', 'cutover'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'stabilize-hypercare',
    name: 'Stabilize / Hypercare',
    domain: 'migration',
    mapLayer: 'operations',
    purpose: 'A defined period of heightened support immediately following go-live.',
    definition: 'Hypercare is a defined, time-boxed period of elevated support immediately after go-live, used to quickly catch and resolve issues before transitioning to normal operations.',
    problemSolved: 'Gives users a safety net immediately after a change, reducing the impact of post-go-live issues.',
    dependsOn: ['validate-phase'],
    usedBy: ['decommission'],
    projectRelevance: ['Hypercare scope, duration, and exit criteria should be agreed in advance, not left open-ended.'],
    pmQuestions: ['What are the defined exit criteria that end hypercare and hand off to normal support?'],
    relatedConcepts: ['validate-phase', 'decommission'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'decommission',
    name: 'Decommission',
    domain: 'migration',
    mapLayer: 'operations',
    purpose: 'Retiring the old system once the new one is confirmed stable.',
    definition: 'Decommissioning is the controlled retirement of the old system or environment once the new one is confirmed stable and accepted.',
    problemSolved: 'Removes ongoing cost and risk of maintaining a legacy system in parallel indefinitely.',
    dependsOn: ['stabilize-hypercare'],
    usedBy: [],
    projectRelevance: ['Decommission timing should be tied to explicit stability criteria, not a guessed calendar date.'],
    pmQuestions: ['What confirms the old system is safe to decommission?'],
    relatedConcepts: ['stabilize-hypercare'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'rollback',
    name: 'Rollback',
    domain: 'migration',
    mapLayer: 'operations',
    purpose: 'A predefined path to revert to the prior state if a change fails.',
    definition: 'Rollback is the predefined process of reverting to the previous known-good state if a change does not succeed.',
    problemSolved: 'Provides a safe exit if a cutover fails, instead of improvising a recovery under pressure.',
    dependsOn: ['backup'],
    usedBy: [],
    projectRelevance: ['Every cutover runbook should define a rollback trigger and the specific steps to execute it.'],
    pmQuestions: ['What specific condition triggers a decision to roll back rather than push forward?'],
    relatedConcepts: ['backup', 'cutover'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'maintenance-window',
    name: 'Maintenance Window',
    domain: 'migration',
    mapLayer: 'operations',
    purpose: 'A scheduled time period during which changes are made, often with reduced availability expected.',
    definition: 'A maintenance window is a pre-agreed time period during which a change is performed, often chosen to minimize business impact.',
    problemSolved: 'Sets clear expectations with the business about when disruption may occur.',
    dependsOn: [],
    usedBy: ['cutover'],
    projectRelevance: ['Requested windows (e.g., a Friday cutover) should be checked against realistic task duration and support availability, not just customer preference.'],
    pmQuestions: ['Does the requested window leave enough time for validation and rollback if needed?'],
    relatedConcepts: ['cutover'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'acceptance-criteria',
    name: 'Acceptance Criteria',
    domain: 'migration',
    mapLayer: 'operations',
    purpose: 'The agreed conditions that must be met for work to be considered complete.',
    definition: 'Acceptance criteria are the specific, agreed conditions a deliverable must meet before the customer accepts it as complete.',
    problemSolved: 'Removes ambiguity about what "done" means, reducing disputes at project closeout.',
    dependsOn: [],
    usedBy: ['validate-phase'],
    projectRelevance: ['Acceptance criteria should be written and agreed before work begins, not defined retroactively at closeout.'],
    pmQuestions: ['Were acceptance criteria agreed with the customer before work started?'],
    relatedConcepts: ['validate-phase'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },

  // ───────────────────────── LICENSING / CSP ─────────────────────────
  {
    id: 'csp',
    name: 'Cloud Solution Provider',
    acronym: 'CSP',
    domain: 'licensing',
    mapLayer: 'operations',
    purpose: 'A Microsoft partner program through which partners sell, provision, and support Microsoft cloud services.',
    definition: 'CSP (Cloud Solution Provider) is a Microsoft partner program that lets partners directly provision, manage, and support customer subscriptions to Microsoft cloud services.',
    problemSolved: 'Lets customers get licensing, billing, and support through a partner relationship instead of directly from Microsoft.',
    dependsOn: [],
    usedBy: [],
    projectRelevance: ['Whether a customer is on CSP, direct, or another agreement type affects who can make licensing changes and how support is escalated. Always verify current program details against official documentation.'],
    pmQuestions: ['What licensing agreement type is this customer under, and who can action license changes?'],
    relatedConcepts: ['sku', 'nce-concept'],
    sourceIds: ['ms900-licensing-support'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'sku',
    name: 'SKU',
    acronym: 'Stock Keeping Unit',
    domain: 'licensing',
    mapLayer: 'operations',
    purpose: 'The identifier for a specific licensed product or plan.',
    definition: 'A SKU (stock keeping unit) is the identifier for a specific licensed product or plan that can be assigned to a user or resource.',
    problemSolved: 'Gives licensing a concrete, assignable unit rather than a vague product name.',
    dependsOn: [],
    usedBy: ['license-assignment'],
    projectRelevance: ['Confirming the exact SKU (not just the marketing name) avoids licensing mismatches during tenant setup. Verify exact SKU names and included features against current Microsoft documentation.'],
    pmQuestions: ['Has the exact SKU been confirmed against what the customer is actually entitled to?'],
    relatedConcepts: ['license-assignment', 'csp'],
    sourceIds: ['ms900-licensing-support'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'license-assignment',
    name: 'License Assignment',
    domain: 'licensing',
    mapLayer: 'operations',
    purpose: 'The act of assigning a purchased license (SKU) to a specific user or resource.',
    definition: 'License assignment is the administrative action of granting a purchased SKU to a specific user or resource so they can use the associated service.',
    problemSolved: 'Connects purchased entitlements to the specific users who need them.',
    dependsOn: ['sku'],
    usedBy: [],
    projectRelevance: ['Licensing can block a project outright if enough licenses have not been purchased or assigned before a pilot or cutover date.'],
    pmQuestions: ['Are enough licenses purchased and assigned to cover the pilot and full rollout population?'],
    retrievalPrompt: 'Why can licensing block a project even when the technical work is ready?',
    relatedConcepts: ['sku', 'csp'],
    sourceIds: ['ms900-licensing-support'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'nce-concept',
    name: 'New Commerce Experience (concept)',
    acronym: 'NCE',
    domain: 'licensing',
    mapLayer: 'operations',
    purpose: 'A Microsoft licensing and purchasing framework that introduced structured terms and commitment options.',
    definition: 'New Commerce Experience (NCE) is the name for Microsoft\'s modernized licensing and purchasing framework, which introduced concepts like term commitments distinct from older month-to-month purchasing.',
    problemSolved: 'Standardizes how subscription terms, commitments, and changes are structured for partners and customers.',
    dependsOn: [],
    usedBy: [],
    projectRelevance: ['Term commitments can limit how quickly licenses can be reduced or changed mid-project — worth confirming before assuming flexibility. Exact terms change and must be verified against current Microsoft licensing documentation.'],
    pmQuestions: ['Is this subscription under a term commitment that limits mid-project changes?'],
    relatedConcepts: ['sku', 'csp'],
    sourceIds: ['ms900-licensing-support'],
    verificationDate: '2026-09-01',
  },

  // ───────────────────────── PROJECT COORDINATION ─────────────────────────
  {
    id: 'scope',
    name: 'Scope',
    domain: 'coordination',
    mapLayer: 'operations',
    purpose: 'The defined boundaries of what a project will and will not deliver.',
    definition: 'Scope defines the specific work, deliverables, and boundaries a project will address — and, implicitly, what it will not.',
    problemSolved: 'Prevents ambiguity and uncontrolled growth of project work (scope creep).',
    dependsOn: [],
    usedBy: ['change-control'],
    projectRelevance: ['Every technical requirement should be checked against agreed scope before being treated as in-flight work.'],
    pmQuestions: ['Is this request within the agreed scope, or does it need to go through change control?'],
    relatedConcepts: ['change-control', 'statement-of-work'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'statement-of-work',
    name: 'Statement of Work',
    acronym: 'SOW',
    domain: 'coordination',
    mapLayer: 'operations',
    purpose: 'The document defining the agreed work, deliverables, and terms for a project.',
    definition: 'A statement of work (SOW) is the document that defines the scope, deliverables, timeline, and terms agreed between the provider and the customer.',
    problemSolved: 'Creates a shared, referenceable agreement of what will be delivered.',
    dependsOn: [],
    usedBy: ['scope'],
    projectRelevance: ['The SOW is the first place to check when a scope question arises.'],
    pmQuestions: ['Does the SOW explicitly cover this deliverable, or is it implied?'],
    relatedConcepts: ['scope'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'raid',
    name: 'RAID (Risks, Assumptions, Issues, Dependencies)',
    acronym: 'RAID',
    domain: 'coordination',
    mapLayer: 'operations',
    purpose: 'A framework for tracking risks, assumptions, issues, and dependencies throughout a project.',
    definition: 'RAID is a project tracking framework covering Risks (things that might happen), Assumptions (things believed true but unconfirmed), Issues (things that have already happened and need resolution), and Dependencies (things this work relies on).',
    problemSolved: 'Gives the project a structured, shared place to track uncertainty and blockers instead of scattering them across conversations.',
    dependsOn: [],
    usedBy: [],
    projectRelevance: ['RAID items should be reviewed regularly, not just logged and forgotten.'],
    pmQuestions: ['Is this a risk (might happen), an issue (already happened), or a dependency (something we are waiting on)?'],
    retrievalPrompt: 'What distinguishes a risk from an issue?',
    scenarioNote: 'Classification is sometimes genuinely context-dependent — a missing dependency can also be a current issue if it is already blocking work.',
    relatedConcepts: ['raci', 'decision-log', 'action-log'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'raci',
    name: 'RACI',
    acronym: 'Responsible, Accountable, Consulted, Informed',
    domain: 'coordination',
    mapLayer: 'operations',
    purpose: 'A model for clarifying roles and decision rights on a project.',
    definition: 'RACI assigns each task or decision a Responsible (does the work), Accountable (owns the outcome), Consulted (gives input), and Informed (kept updated) party.',
    problemSolved: 'Removes ambiguity about who actually owns a decision versus who simply needs to know about it.',
    dependsOn: [],
    usedBy: [],
    projectRelevance: ['A RACI matrix is a natural translation of military task organization into civilian project terms.'],
    pmQuestions: ['Who is Accountable for this decision, distinct from who is doing the work?'],
    relatedConcepts: ['raid'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'decision-log',
    name: 'Decision Log',
    domain: 'coordination',
    mapLayer: 'operations',
    purpose: 'A record of key project decisions, who made them, and why.',
    definition: 'A decision log records significant project decisions along with who made them, when, and the rationale.',
    problemSolved: 'Prevents re-litigating settled decisions and preserves context for later team members.',
    dependsOn: [],
    usedBy: [],
    projectRelevance: ['A decision log is often the fastest way to answer "why did we do it this way?" months later.'],
    pmQuestions: ['Was this decision logged, or only discussed verbally?'],
    relatedConcepts: ['raid', 'action-log'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'action-log',
    name: 'Action Log',
    domain: 'coordination',
    mapLayer: 'operations',
    purpose: 'A tracked list of open tasks with owners and due dates.',
    definition: 'An action log tracks specific, assigned tasks with an owner and target date, separate from broader project milestones.',
    problemSolved: 'Keeps small but necessary tasks from falling through the cracks between meetings.',
    dependsOn: [],
    usedBy: [],
    projectRelevance: ['Reviewing the action log at each status meeting is a basic accountability mechanism.'],
    pmQuestions: ['Does every open action have a named owner and a due date?'],
    relatedConcepts: ['raid', 'decision-log'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'change-control',
    name: 'Change Control',
    domain: 'coordination',
    mapLayer: 'operations',
    purpose: 'A formal process for proposing, evaluating, and approving changes to scope, schedule, or approach.',
    definition: 'Change control is the formal process for proposing, evaluating, and approving changes to a project\'s scope, schedule, cost, or approach.',
    problemSolved: 'Prevents uncontrolled scope creep by requiring changes to be evaluated and agreed before being actioned.',
    dependsOn: ['scope'],
    usedBy: [],
    projectRelevance: ['A request that expands scope should go through change control, not be quietly absorbed into existing work.'],
    pmQuestions: ['Has this change been formally logged and approved, or just verbally agreed?'],
    relatedConcepts: ['scope'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'communication-plan',
    name: 'Communication Plan',
    domain: 'coordination',
    mapLayer: 'operations',
    purpose: 'A defined plan for what will be communicated, to whom, how, and when during a project.',
    definition: 'A communication plan defines what information will be shared, with whom, through what channel, and on what cadence throughout a project.',
    problemSolved: 'Prevents stakeholders from being surprised by changes that affect them, especially during cutover.',
    dependsOn: [],
    usedBy: ['cutover'],
    projectRelevance: ['White-glove or executive-impacting changes especially need a clear, proactive communication plan.'],
    pmQuestions: ['Who needs advance notice of this change, and has that communication gone out?'],
    relatedConcepts: ['cutover'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
  {
    id: 'cutover-runbook',
    name: 'Cutover Runbook',
    domain: 'coordination',
    mapLayer: 'operations',
    purpose: 'The detailed, sequenced plan executed during a cutover.',
    definition: 'A cutover runbook is the detailed, sequenced execution plan for a cutover, listing tasks, owners, timing, validation steps, and rollback actions.',
    problemSolved: 'Turns a cutover from an improvised effort into a rehearsed, trackable sequence of steps.',
    dependsOn: ['cutover'],
    usedBy: [],
    projectRelevance: ['A well-built runbook is the single most useful artifact for a coordinator during go-live.'],
    pmQuestions: ['Has the runbook been reviewed (rehearsed) with all task owners before the actual cutover?'],
    relatedConcepts: ['cutover', 'rollback'],
    sourceIds: ['az900-architecture'],
    verificationDate: '2026-09-01',
  },
]

export const conceptById = new Map(concepts.map((c) => [c.id, c]))
