import type { Question } from './types'

// Deterministic seed content — no runtime generation. Ordering here is the
// stable base order; the drill view applies a seeded shuffle so review
// sessions stay reproducible for testing.
export const questions: Question[] = [
  // ── Foundation ──
  {
    id: 'q-found-1',
    conceptIds: ['authentication', 'authorization'],
    type: 'multiple-choice',
    prompt: 'A user enters a valid password but is denied access to a specific report. Which concept explains the denial?',
    choices: ['Authentication', 'Authorization', 'DNS resolution', 'Backup'],
    answer: 'Authorization',
    explanation: 'Authentication confirmed who the user is; authorization determines what they are allowed to access, and denied it here.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-found-2',
    conceptIds: ['dns'],
    type: 'fill-in',
    prompt: 'Fill in the blank: ___ translates domain names into IP addresses and hosts records used to verify domain ownership.',
    answer: 'DNS',
    explanation: 'DNS (Domain Name System) resolves names to addresses and hosts records like MX and TXT.',
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'q-found-3',
    conceptIds: ['rpo', 'rto'],
    type: 'matching',
    prompt: 'Which term describes "maximum acceptable data loss, measured in time"?',
    choices: ['RPO', 'RTO', 'HA', 'DR'],
    answer: 'RPO',
    explanation: 'RPO (Recovery Point Objective) is about how much data loss is acceptable; RTO is about how fast recovery must happen.',
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'q-found-4',
    conceptIds: ['rpo', 'rto'],
    type: 'matching',
    prompt: 'Which term describes "maximum acceptable time to restore a system"?',
    choices: ['RPO', 'RTO', 'SLA', 'CMDB'],
    answer: 'RTO',
    explanation: 'RTO (Recovery Time Objective) is a time-to-restore target.',
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'q-found-5',
    conceptIds: ['backup'],
    type: 'pm-judgment',
    prompt: 'A vendor reports the nightly backup job "completed successfully." What should a coordinator confirm next?',
    choices: [
      'That the backup is actually restorable, not just that the job finished',
      'The exact file size of the backup',
      'Nothing further — completion is sufficient',
      'That the backup ran at the same time as last week',
    ],
    answer: 'That the backup is actually restorable, not just that the job finished',
    explanation: 'A completed job is not proof of a usable recovery point. Restore testing is what actually validates a backup.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-found-6',
    conceptIds: ['high-availability', 'disaster-recovery'],
    type: 'multiple-choice',
    prompt: 'High availability and disaster recovery are related but distinct. What is the key difference?',
    choices: [
      'HA reduces impact of component failure during normal operation; DR is the plan to recover after a major disruption',
      'HA and DR are the same thing with different names',
      'DR only applies to on-premises systems',
      'HA is a Microsoft product; DR is not',
    ],
    answer: 'HA reduces impact of component failure during normal operation; DR is the plan to recover after a major disruption',
    explanation: 'HA is about resilience during operation; DR is the recovery process after a significant failure.',
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'q-found-7',
    conceptIds: ['api'],
    type: 'acronym',
    prompt: 'What does API stand for?',
    choices: ['Application Programming Interface', 'Automated Process Integration', 'Application Process Index', 'Active Protocol Interchange'],
    answer: 'Application Programming Interface',
    explanation: 'An API is a defined contract that lets software components communicate.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-found-8',
    conceptIds: ['application', 'discover-phase'],
    type: 'pm-judgment',
    prompt: 'Before migrating a business application, what is the biggest risk if discovery was skipped?',
    choices: [
      'Undocumented dependencies (integrations, APIs) break unexpectedly during cutover',
      'The application will run slightly slower',
      'The project will finish early',
      'Licensing costs will decrease',
    ],
    answer: 'Undocumented dependencies (integrations, APIs) break unexpectedly during cutover',
    explanation: 'Skipped discovery is a leading cause of migration-day surprises from unknown dependencies.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-found-9',
    conceptIds: ['client-server'],
    type: 'multiple-choice',
    prompt: 'In the client/server model, what does the server do?',
    choices: ['Requests a service', 'Provides a service to requesting clients', 'Only stores backups', 'Only manages DNS'],
    answer: 'Provides a service to requesting clients',
    explanation: 'The server hosts and provides the service; the client requests it.',
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'q-found-10',
    conceptIds: ['database'],
    type: 'pm-judgment',
    prompt: 'A SQL database migration is planned. What should be confirmed before cutover?',
    choices: [
      'Compatibility between source and target database versions',
      'The database\'s marketing name',
      'Whether the vendor has a logo',
      'The number of tables, regardless of complexity',
    ],
    answer: 'Compatibility between source and target database versions',
    explanation: 'Version and compatibility gaps are a common cause of failed database migrations.',
    sourceIds: ['az900-architecture'],
  },

  // ── Cloud / AZ-900 ──
  {
    id: 'q-cloud-1',
    conceptIds: ['iaas-paas-saas'],
    type: 'acronym',
    prompt: 'Microsoft 365 is delivered under which cloud service model?',
    choices: ['IaaS', 'PaaS', 'SaaS', 'On-premises'],
    answer: 'SaaS',
    explanation: 'Microsoft 365 is a ready-to-use application delivered as Software as a Service.',
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'q-cloud-2',
    conceptIds: ['shared-responsibility'],
    type: 'multiple-choice',
    prompt: 'Under the shared responsibility model, what shifts as you move from IaaS to SaaS?',
    choices: [
      'The customer manages progressively less of the stack as the provider manages more',
      'The customer always manages 100% regardless of service model',
      'Nothing changes between models',
      'The provider takes on zero responsibility',
    ],
    answer: 'The customer manages progressively less of the stack as the provider manages more',
    explanation: 'As you move IaaS → PaaS → SaaS, the provider assumes more operational responsibility.',
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'q-cloud-3',
    conceptIds: ['azure-tenant', 'azure-subscription', 'resource-group', 'azure-resource'],
    type: 'ordering',
    prompt: 'Order the Azure hierarchy from broadest to most specific.',
    choices: ['Tenant', 'Subscription', 'Resource Group', 'Resource'],
    answer: ['Tenant', 'Subscription', 'Resource Group', 'Resource'],
    explanation: 'A tenant contains subscriptions, which contain resource groups, which contain resources.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-cloud-4',
    conceptIds: ['management-group', 'azure-subscription'],
    type: 'multiple-choice',
    prompt: 'What sits above subscriptions in the Azure governance hierarchy?',
    choices: ['Management group', 'Resource group', 'Resource lock', 'Availability zone'],
    answer: 'Management group',
    explanation: 'Management groups apply governance across multiple subscriptions.',
    sourceIds: ['az900-governance'],
  },
  {
    id: 'q-cloud-5',
    conceptIds: ['rbac', 'azure-policy'],
    type: 'multiple-choice',
    prompt: 'What is the key difference between RBAC and Azure Policy?',
    choices: [
      'RBAC controls who can do what; Azure Policy controls what configurations are allowed',
      'They are two names for the same feature',
      'RBAC only applies to Microsoft 365, not Azure',
      'Azure Policy replaces the need for identity entirely',
    ],
    answer: 'RBAC controls who can do what; Azure Policy controls what configurations are allowed',
    explanation: 'RBAC is about access; Azure Policy is about compliance and configuration standards.',
    sourceIds: ['az900-governance'],
  },
  {
    id: 'q-cloud-6',
    conceptIds: ['resource-locks'],
    type: 'pm-judgment',
    prompt: 'A planned cutover step unexpectedly fails to modify a resource. What should be checked first?',
    choices: ['Whether a resource lock is preventing the change', 'Whether the internet is down', 'Whether the resource was ever created', 'Whether the tenant exists'],
    answer: 'Whether a resource lock is preventing the change',
    explanation: 'Resource locks can silently block changes even for users with sufficient permissions.',
    sourceIds: ['az900-governance'],
  },
  {
    id: 'q-cloud-7',
    conceptIds: ['consumption-model', 'cost-management'],
    type: 'pm-judgment',
    prompt: 'A project closes out and moves to normal operations. What is a common gap to avoid?',
    choices: [
      'No one is assigned to monitor ongoing cloud cost after go-live',
      'The tenant is deleted automatically',
      'Cost management is unavailable in Azure',
      'Consumption-based billing does not apply after go-live',
    ],
    answer: 'No one is assigned to monitor ongoing cloud cost after go-live',
    explanation: 'Cost ownership after closeout should be explicitly assigned, since consumption-based billing continues indefinitely.',
    sourceIds: ['az900-governance'],
  },
  {
    id: 'q-cloud-8',
    conceptIds: ['vnet', 'ip-addressing'],
    type: 'pm-judgment',
    prompt: 'Before building hybrid connectivity between on-prem and an Azure VNet, what must be checked?',
    choices: ['That IP address ranges do not overlap', 'That the VNet has a friendly name', 'That the region has multiple availability zones', 'That Azure Policy is disabled'],
    answer: 'That IP address ranges do not overlap',
    explanation: 'Overlapping IP ranges between on-prem and Azure will break routing for hybrid connectivity.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-cloud-9',
    conceptIds: ['azure-regions'],
    type: 'multiple-choice',
    prompt: 'What is an availability zone?',
    choices: [
      'A physically separate location within some Azure regions, used to increase resiliency',
      'A synonym for subscription',
      'A billing category',
      'A type of virtual machine',
    ],
    answer: 'A physically separate location within some Azure regions, used to increase resiliency',
    explanation: 'Availability zones are physically separate datacenter groupings within certain regions.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-cloud-10',
    conceptIds: ['cloud-deployment-models'],
    type: 'current-target',
    prompt: 'A customer runs their file server on a local rack and wants to keep it that way while adopting Microsoft 365 for email. What best describes their target architecture?',
    choices: ['Fully cloud', 'Hybrid', 'Fully on-premises', 'Multi-cloud'],
    answer: 'Hybrid',
    explanation: 'Keeping some infrastructure on-prem while adopting cloud services for other workloads is a hybrid model.',
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'q-cloud-11',
    conceptIds: ['storage'],
    type: 'pm-judgment',
    prompt: 'What should drive the choice of Azure Storage redundancy level for a given dataset?',
    choices: ['The actual business requirement for data durability and availability', 'Whichever option is listed first in the portal', 'The color scheme of the app', 'The size of the marketing team'],
    answer: 'The actual business requirement for data durability and availability',
    explanation: 'Redundancy should be a deliberate decision tied to business need, not a default choice.',
    sourceIds: ['az900-architecture'],
  },

  // ── Microsoft 365 ──
  {
    id: 'q-m365-1',
    conceptIds: ['onedrive', 'sharepoint-online'],
    type: 'multiple-choice',
    prompt: 'What is the key difference between OneDrive and SharePoint Online?',
    choices: [
      'OneDrive is personal storage per user; SharePoint is shared team/site storage',
      'They are the same product with different names',
      'SharePoint is only for email',
      'OneDrive requires a separate tenant',
    ],
    answer: 'OneDrive is personal storage per user; SharePoint is shared team/site storage',
    explanation: 'OneDrive is scoped to the individual user; SharePoint sites are shared across a team or organization.',
    sourceIds: ['ab900-what-is-m365'],
  },
  {
    id: 'q-m365-2',
    conceptIds: ['exchange-online', 'dns'],
    type: 'pm-judgment',
    prompt: 'Before cutting mail over to Exchange Online, what dependency must be resolved?',
    choices: ['DNS record changes (MX, TXT) with whoever controls the zone', 'The color theme of Outlook', 'The number of Teams channels', 'Whether OneDrive quotas are set'],
    answer: 'DNS record changes (MX, TXT) with whoever controls the zone',
    explanation: 'Mail routing depends on DNS records, and the DNS owner may be an external party requiring lead time.',
    sourceIds: ['ab900-what-is-m365'],
  },
  {
    id: 'q-m365-3',
    conceptIds: ['exchange-online'],
    type: 'pm-judgment',
    prompt: 'Why would a Microsoft 365 mail migration use a pilot mailbox cohort before full cutover?',
    choices: [
      'To validate the migration approach on a small, representative group before broad impact',
      'Because Microsoft requires it by law',
      'To reduce the number of licenses needed permanently',
      'Pilots are only cosmetic and have no technical value',
    ],
    answer: 'To validate the migration approach on a small, representative group before broad impact',
    explanation: 'A pilot surfaces issues on a small scale before they affect the full user population.',
    sourceIds: ['ab900-what-is-m365'],
  },
  {
    id: 'q-m365-4',
    conceptIds: ['teams', 'sharepoint-online'],
    type: 'multiple-choice',
    prompt: 'Microsoft Teams integrates with which other Microsoft 365 workload for file storage behind the scenes?',
    choices: ['SharePoint Online', 'Azure Sentinel', 'Azure Policy', 'Defender for Cloud'],
    answer: 'SharePoint Online',
    explanation: 'Files shared in Teams channels are stored in the associated SharePoint site.',
    sourceIds: ['ab900-what-is-m365'],
  },
  {
    id: 'q-m365-5',
    conceptIds: ['m365-admin-center'],
    type: 'fill-in',
    prompt: 'Fill in the blank: The ___ ___ ___ is the primary console for managing users, licenses, and tenant-wide Microsoft 365 settings.',
    answer: 'Microsoft 365 Admin Center',
    explanation: 'The Microsoft 365 admin center is the central management console, with links to specialized admin centers.',
    sourceIds: ['m365-admin-path'],
  },
  {
    id: 'q-m365-6',
    conceptIds: ['service-health'],
    type: 'pm-judgment',
    prompt: 'Users report a Teams outage right after your change window. What should be checked first?',
    choices: [
      'Microsoft 365 Service Health, to rule out a broader Microsoft-side incident',
      'Whether to immediately roll back regardless of cause',
      'The user\'s personal internet plan',
      'Nothing — always assume the project caused it',
    ],
    answer: 'Microsoft 365 Service Health, to rule out a broader Microsoft-side incident',
    explanation: 'Checking Service Health quickly distinguishes a tenant-side issue from a broader Microsoft service event.',
    sourceIds: ['m365-admin-path'],
  },
  {
    id: 'q-m365-7',
    conceptIds: ['m365-ecosystem'],
    type: 'acronym',
    prompt: 'What does M365 stand for?',
    choices: ['Microsoft 365', 'Multi-cloud 365', 'Managed 365 Services', 'Microsoft Enterprise 365'],
    answer: 'Microsoft 365',
    explanation: 'M365 is shorthand for Microsoft 365.',
    sourceIds: ['ab900-what-is-m365'],
  },
  {
    id: 'q-m365-8',
    conceptIds: ['m365-apps'],
    type: 'multiple-choice',
    prompt: 'What are "Microsoft 365 Apps"?',
    choices: [
      'The installable desktop/mobile Office applications like Word, Excel, and Outlook',
      'A synonym for the M365 admin center',
      'A licensing agreement type',
      'A security product',
    ],
    answer: 'The installable desktop/mobile Office applications like Word, Excel, and Outlook',
    explanation: 'Microsoft 365 Apps refers to the installable productivity applications included with many plans.',
    sourceIds: ['ab900-what-is-m365'],
  },

  // ── Identity ──
  {
    id: 'q-id-1',
    conceptIds: ['ad-ds', 'entra-id'],
    type: 'multiple-choice',
    prompt: 'How does AD DS differ from Entra ID?',
    choices: [
      'AD DS is the traditional on-premises directory; Entra ID is Microsoft\'s cloud identity service',
      'They are identical products with different names only',
      'Entra ID only works without any internet connection',
      'AD DS is used exclusively for Microsoft 365 licensing',
    ],
    answer: 'AD DS is the traditional on-premises directory; Entra ID is Microsoft\'s cloud identity service',
    explanation: 'AD DS is on-prem; Entra ID is cloud-based, and the two can be connected via hybrid identity.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-id-2',
    conceptIds: ['hybrid-identity', 'entra-connect'],
    type: 'fill-in',
    prompt: 'Fill in the blank: In a hybrid identity model, ___ ___ synchronizes identities from on-premises AD DS to Entra ID.',
    answer: 'Microsoft Entra Connect',
    explanation: 'Entra Connect (formerly Azure AD Connect) is the sync tool for hybrid identity.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-id-3',
    conceptIds: ['entra-id'],
    type: 'multiple-choice',
    prompt: 'Entra ID was previously known by what name?',
    choices: ['Azure Active Directory', 'Active Directory Domain Services', 'Office 365 Directory', 'Windows Directory Service'],
    answer: 'Azure Active Directory',
    explanation: 'Microsoft renamed Azure Active Directory (Azure AD) to Microsoft Entra ID.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-id-4',
    conceptIds: ['conditional-access'],
    type: 'pm-judgment',
    prompt: 'What must a coordinator clarify before broad Conditional Access enforcement?',
    choices: [
      'Pilot scope, break-glass account exclusions, and legacy application exceptions',
      'The font used in the sign-in page',
      'Whether Teams chat colors can be customized',
      'Nothing — enforcement can happen immediately for everyone',
    ],
    answer: 'Pilot scope, break-glass account exclusions, and legacy application exceptions',
    explanation: 'Conditional Access changes access immediately for everyone in scope, so exceptions and a pilot must be planned first.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-id-5',
    conceptIds: ['mfa'],
    type: 'acronym',
    prompt: 'What does MFA stand for?',
    choices: ['Multi-Factor Authentication', 'Managed File Access', 'Multiple Federated Accounts', 'Master File Authorization'],
    answer: 'Multi-Factor Authentication',
    explanation: 'MFA requires more than one form of verification.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-id-6',
    conceptIds: ['sso'],
    type: 'acronym',
    prompt: 'What does SSO stand for, and what does it do?',
    choices: [
      'Single Sign-On — authenticate once, access multiple integrated apps',
      'Secure Session Override — bypasses authentication entirely',
      'System Security Oversight — a monitoring tool',
      'Server Sync Operation — a data replication process',
    ],
    answer: 'Single Sign-On — authenticate once, access multiple integrated apps',
    explanation: 'SSO lets a user authenticate once and access multiple integrated applications.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-id-7',
    conceptIds: ['least-privilege', 'rbac'],
    type: 'pm-judgment',
    prompt: 'During an access review as part of a migration project, what is a good practice?',
    choices: [
      'Use the opportunity to right-size access to least privilege, not just replicate existing access',
      'Always grant admin access to speed up the project',
      'Skip the review — it is out of scope for any migration',
      'Only reduce access for departed employees',
    ],
    answer: 'Use the opportunity to right-size access to least privilege, not just replicate existing access',
    explanation: 'Migrations are a natural opportunity to correct over-provisioned access rather than just copy it forward.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-id-8',
    conceptIds: ['conditional-access'],
    type: 'dependency',
    prompt: 'Conditional Access policy decisions can depend on device compliance state. Which service provides that signal?',
    choices: ['Intune', 'Exchange Online', 'Azure Policy', 'Purview'],
    answer: 'Intune',
    explanation: 'Intune compliance policies provide the device-state signal Conditional Access can evaluate.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-id-9',
    conceptIds: ['entra-connect'],
    type: 'pm-judgment',
    prompt: 'Before a migration wave that depends on current identity data, what should be confirmed?',
    choices: ['That Entra Connect sync last ran successfully and on schedule', 'That the tenant name is memorable', 'That MFA is disabled for convenience', 'That Teams is installed on all devices'],
    answer: 'That Entra Connect sync last ran successfully and on schedule',
    explanation: 'Stale or failed sync means the cloud directory does not reflect current on-prem identity state.',
    sourceIds: ['sc900-cert'],
  },

  // ── Endpoint Management ──
  {
    id: 'q-ep-1',
    conceptIds: ['mdm', 'mam'],
    type: 'multiple-choice',
    prompt: 'How does MDM differ from MAM?',
    choices: [
      'MDM manages the whole device; MAM manages specific apps and their data without full device control',
      'MDM only applies to iPhones; MAM only applies to Windows',
      'They are interchangeable terms for the same capability',
      'MAM requires more device control than MDM',
    ],
    answer: 'MDM manages the whole device; MAM manages specific apps and their data without full device control',
    explanation: 'MDM is full device management; MAM is scoped to applications, common for BYOD.',
    sourceIds: ['m365-admin-path'],
  },
  {
    id: 'q-ep-2',
    conceptIds: ['intune', 'conditional-access'],
    type: 'multiple-choice',
    prompt: 'For 800 laptops that must be compliant before stricter Conditional Access is enforced, what is the correct sequence?',
    choices: [
      'Enroll and reach an acceptable compliance rate first, then enforce access based on compliance',
      'Enforce access immediately, then enroll devices afterward',
      'Skip enrollment — Conditional Access does not need device signal',
      'Enroll only executives\' devices and enforce for everyone',
    ],
    answer: 'Enroll and reach an acceptable compliance rate first, then enforce access based on compliance',
    explanation: 'Endpoint readiness must precede enforcement, or compliant users get locked out unnecessarily.',
    sourceIds: ['m365-admin-path'],
  },
  {
    id: 'q-ep-3',
    conceptIds: ['autopilot'],
    type: 'pm-judgment',
    prompt: 'A device refresh project plans to use Windows Autopilot. What is a commonly overlooked prerequisite?',
    choices: [
      'Registering device hardware IDs ahead of the rollout date',
      'Choosing a wallpaper for the new devices',
      'Autopilot has no prerequisites',
      'Disabling Intune first',
    ],
    answer: 'Registering device hardware IDs ahead of the rollout date',
    explanation: 'Devices must be registered with their hardware IDs before Autopilot can provision them automatically.',
    sourceIds: ['m365-admin-path'],
  },
  {
    id: 'q-ep-4',
    conceptIds: ['compliance-policy'],
    type: 'fill-in',
    prompt: 'Fill in the blank: A ___ ___ in Intune defines conditions a device must meet, such as encryption or OS version, to be marked compliant.',
    answer: 'compliance policy',
    explanation: 'Compliance policies define the required device state.',
    sourceIds: ['m365-admin-path'],
  },
  {
    id: 'q-ep-5',
    conceptIds: ['configuration-profiles'],
    type: 'pm-judgment',
    prompt: 'Before deploying a new configuration profile fleet-wide, what should happen first?',
    choices: ['Validate it on a pilot device group', 'Deploy to all devices immediately for speed', 'Skip validation to save time', 'Only test on personal devices'],
    answer: 'Validate it on a pilot device group',
    explanation: 'Piloting a configuration profile avoids fleet-wide misconfiguration from an untested setting.',
    sourceIds: ['m365-admin-path'],
  },

  // ── Security ──
  {
    id: 'q-sec-1',
    conceptIds: ['zero-trust'],
    type: 'multiple-choice',
    prompt: 'What is the core idea of Zero Trust?',
    choices: [
      'Explicitly verify every access request rather than trusting anything by default based on network location',
      'Trust all devices inside the corporate network automatically',
      'Disable all authentication to speed up access',
      'Only applies to external users, never internal ones',
    ],
    answer: 'Explicitly verify every access request rather than trusting anything by default based on network location',
    explanation: 'Zero Trust replaces perimeter-based trust with continuous, explicit verification.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-sec-2',
    conceptIds: ['sentinel', 'siem'],
    type: 'acronym',
    prompt: 'Microsoft Sentinel is best described as which type of tool?',
    choices: ['Cloud-native SIEM/SOAR', 'Endpoint antivirus only', 'A licensing console', 'A DNS management tool'],
    answer: 'Cloud-native SIEM/SOAR',
    explanation: 'Sentinel is Microsoft\'s cloud-native SIEM and SOAR service.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-sec-3',
    conceptIds: ['siem'],
    type: 'multiple-choice',
    prompt: 'What is the difference between a SIEM and a SOC?',
    choices: [
      'A SIEM is the tooling that aggregates security signal; a SOC is the team that monitors and responds to it',
      'They are the same thing',
      'A SOC is software; a SIEM is a team',
      'SIEM only applies to Microsoft 365, not Azure',
    ],
    answer: 'A SIEM is the tooling that aggregates security signal; a SOC is the team that monitors and responds to it',
    explanation: 'SIEM = tooling; SOC = the people/process that act on what the tooling surfaces.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-sec-4',
    conceptIds: ['defender-office', 'exchange-online'],
    type: 'pm-judgment',
    prompt: 'Before mailboxes go live on Exchange Online, what security configuration should be confirmed?',
    choices: [
      'Anti-phishing and safe-links policies in Defender for Office 365 are configured',
      'The mailbox theme color',
      'Whether Teams is installed',
      'Whether OneDrive sync is disabled',
    ],
    answer: 'Anti-phishing and safe-links policies in Defender for Office 365 are configured',
    explanation: 'Threat protection should be configured before go-live, not left until after an incident.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-sec-5',
    conceptIds: ['purview'],
    type: 'pm-judgment',
    prompt: 'A migration plans to bulk-delete old mailbox content. What should be checked first?',
    choices: [
      'Whether Purview retention or DLP policies restrict what can be deleted',
      'Whether the mailbox owner likes the plan',
      'The color of the deletion confirmation dialog',
      'Nothing — deletion is always safe to perform freely',
    ],
    answer: 'Whether Purview retention or DLP policies restrict what can be deleted',
    explanation: 'Retention and DLP policies can legally or technically constrain what a migration is allowed to delete.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-sec-6',
    conceptIds: ['defender-family'],
    type: 'multiple-choice',
    prompt: 'What does the Microsoft Defender product family cover, at a conceptual level?',
    choices: [
      'A connected set of threat protection products spanning endpoints, email, and cloud',
      'Only antivirus for Windows 7',
      'A licensing agreement type',
      'A single product that replaces all identity tools',
    ],
    answer: 'A connected set of threat protection products spanning endpoints, email, and cloud',
    explanation: 'Defender is a family of connected security products, not a single point tool.',
    sourceIds: ['sc900-cert'],
  },

  // ── Migration Delivery ──
  {
    id: 'q-mig-1',
    conceptIds: ['discover-phase', 'assess-phase', 'design-phase', 'pilot-phase', 'cutover', 'validate-phase', 'stabilize-hypercare', 'decommission'],
    type: 'ordering',
    prompt: 'Order the migration lifecycle phases.',
    choices: ['Discover', 'Assess', 'Design', 'Pilot', 'Cutover', 'Validate', 'Hypercare', 'Decommission'],
    answer: ['Discover', 'Assess', 'Design', 'Pilot', 'Cutover', 'Validate', 'Hypercare', 'Decommission'],
    explanation: 'This is the general delivery sequence used throughout the app\'s migration content.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-mig-2',
    conceptIds: ['rollback'],
    type: 'multiple-choice',
    prompt: 'What is a rollback?',
    choices: [
      'A predefined process to revert to the previous known-good state if a change fails',
      'A synonym for hypercare',
      'A type of licensing agreement',
      'A step that only applies after decommissioning',
    ],
    answer: 'A predefined process to revert to the previous known-good state if a change fails',
    explanation: 'Rollback is the planned path back to the prior state, not an improvised reaction.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-mig-3',
    conceptIds: ['stabilize-hypercare'],
    type: 'pm-judgment',
    prompt: 'What should be defined before hypercare begins?',
    choices: ['The exit criteria that end hypercare and hand off to normal support', 'Nothing — hypercare has no defined end', 'Only the start date', 'The vendor\'s stock price'],
    answer: 'The exit criteria that end hypercare and hand off to normal support',
    explanation: 'Hypercare should be time-boxed with clear exit criteria, not open-ended.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-mig-4',
    conceptIds: ['maintenance-window', 'cutover'],
    type: 'pm-judgment',
    prompt: 'A customer requests a tight Friday evening cutover window. What should a coordinator check?',
    choices: [
      'Whether the window leaves enough margin for validation and rollback if something goes wrong',
      'Whether Friday is anyone\'s favorite day',
      'Nothing — always accept the requested date',
      'Whether the vendor has a weekend office',
    ],
    answer: 'Whether the window leaves enough margin for validation and rollback if something goes wrong',
    explanation: 'A tight window with no rollback margin is a real schedule risk that should be raised, not silently accepted.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-mig-5',
    conceptIds: ['acceptance-criteria'],
    type: 'pm-judgment',
    prompt: 'When should acceptance criteria be defined?',
    choices: ['Before work begins, agreed with the customer', 'Only at project closeout', 'Never — they are optional', 'After the invoice is sent'],
    answer: 'Before work begins, agreed with the customer',
    explanation: 'Defining acceptance criteria upfront avoids disputes about what "done" means at closeout.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-mig-6',
    conceptIds: ['pilot-phase'],
    type: 'pm-judgment',
    prompt: 'A pilot group is chosen entirely from the easiest, most tech-savvy users. What is the risk?',
    choices: [
      'The pilot will not surface issues that affect edge cases like executives or specialized roles',
      'There is no risk — easier users always represent everyone',
      'The pilot will take longer than necessary',
      'Pilots should always exclude technical users',
    ],
    answer: 'The pilot will not surface issues that affect edge cases like executives or specialized roles',
    explanation: 'A representative pilot should include edge cases, not just the easiest users.',
    sourceIds: ['az900-architecture'],
  },

  // ── Licensing / CSP ──
  {
    id: 'q-lic-1',
    conceptIds: ['license-assignment'],
    type: 'pm-judgment',
    prompt: 'Why can licensing block a project even when the technical work is ready?',
    choices: [
      'Without enough purchased and assigned licenses, users cannot actually use the service',
      'Licensing never affects technical readiness',
      'Licenses are automatically assigned by default',
      'Technical readiness always overrides licensing requirements',
    ],
    answer: 'Without enough purchased and assigned licenses, users cannot actually use the service',
    explanation: 'Even a technically ready environment cannot onboard users without sufficient assigned licenses.',
    sourceIds: ['ms900-licensing-support'],
  },
  {
    id: 'q-lic-2',
    conceptIds: ['csp'],
    type: 'acronym',
    prompt: 'What does CSP stand for in a Microsoft licensing context?',
    choices: ['Cloud Solution Provider', 'Customer Support Program', 'Certified Systems Partner', 'Cloud Security Platform'],
    answer: 'Cloud Solution Provider',
    explanation: 'CSP is a Microsoft partner program for provisioning and supporting customer subscriptions.',
    sourceIds: ['ms900-licensing-support'],
  },
  {
    id: 'q-lic-3',
    conceptIds: ['nce-concept'],
    type: 'pm-judgment',
    prompt: 'A customer wants to reduce license count mid-project. What should be checked?',
    choices: [
      'Whether the subscription is under a term commitment that limits changes',
      'Nothing — reductions are always immediate and free',
      'Whether the customer\'s favorite color is blue',
      'Whether Microsoft has been notified verbally',
    ],
    answer: 'Whether the subscription is under a term commitment that limits changes',
    explanation: 'Term commitments under NCE-style agreements can constrain when licenses can be reduced. Always verify current terms.',
    sourceIds: ['ms900-licensing-support'],
  },
  {
    id: 'q-lic-4',
    conceptIds: ['sku'],
    type: 'acronym',
    prompt: 'What does SKU stand for?',
    choices: ['Stock Keeping Unit', 'System Key Utility', 'Standard Kernel Update', 'Secure Key Usage'],
    answer: 'Stock Keeping Unit',
    explanation: 'A SKU identifies a specific licensed product or plan.',
    sourceIds: ['ms900-licensing-support'],
  },

  // ── Project Coordination ──
  {
    id: 'q-coord-1',
    conceptIds: ['raid'],
    type: 'raid-classify',
    prompt: 'Classify: "The customer has not supplied tenant admin access and configuration starts tomorrow."',
    choices: ['Risk', 'Assumption', 'Issue', 'Dependency', 'Issue and/or Dependency (context-dependent)'],
    answer: 'Issue and/or Dependency (context-dependent)',
    explanation: 'This is already blocking (an Issue) and something the work relies on (a Dependency) — classification can depend on exact wording and timing, and that ambiguity should be named rather than forced.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-coord-2',
    conceptIds: ['raid'],
    type: 'raid-classify',
    prompt: 'Classify: "We believe the customer\'s DNS provider allows same-day record changes, but this has not been confirmed."',
    choices: ['Risk', 'Assumption', 'Issue', 'Dependency'],
    answer: 'Assumption',
    explanation: 'This is believed true but unconfirmed — a textbook assumption that should be validated before relying on it.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-coord-3',
    conceptIds: ['raid'],
    type: 'raid-classify',
    prompt: 'Classify: "There is a chance the pilot group will surface unexpected app compatibility problems."',
    choices: ['Risk', 'Assumption', 'Issue', 'Dependency'],
    answer: 'Risk',
    explanation: 'This is something that might happen, not something confirmed or already occurring — a risk.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-coord-4',
    conceptIds: ['raid'],
    type: 'raid-classify',
    prompt: 'Classify: "The migration cannot start until the customer\'s external MSP completes the DNS cutover."',
    choices: ['Risk', 'Assumption', 'Issue', 'Dependency'],
    answer: 'Dependency',
    explanation: 'This is something the work relies on from outside the project team — a dependency.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-coord-5',
    conceptIds: ['raci'],
    type: 'multiple-choice',
    prompt: 'In RACI, what is the difference between Responsible and Accountable?',
    choices: [
      'Responsible does the work; Accountable owns the outcome',
      'They are the same role',
      'Accountable does the work; Responsible only observes',
      'Responsible is always the project sponsor',
    ],
    answer: 'Responsible does the work; Accountable owns the outcome',
    explanation: 'Accountable is the single owner of the outcome, even if someone else (Responsible) executes the work.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-coord-6',
    conceptIds: ['change-control', 'scope'],
    type: 'pm-judgment',
    prompt: 'A customer asks for an additional workload to be migrated that was not in the original SOW. What should happen?',
    choices: [
      'Route it through change control rather than quietly absorbing it into current scope',
      'Do it immediately without documentation to keep the customer happy',
      'Refuse it outright with no discussion',
      'Ignore the request entirely',
    ],
    answer: 'Route it through change control rather than quietly absorbing it into current scope',
    explanation: 'Change control formally evaluates and approves scope changes instead of letting scope creep in unmanaged.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-coord-7',
    conceptIds: ['communication-plan'],
    type: 'pm-judgment',
    prompt: 'A migration will affect 20 executives with white-glove support needs. What should exist before cutover?',
    choices: [
      'A proactive communication plan specifically addressing their needs and timing',
      'Nothing special — treat them like every other user',
      'A verbal heads-up the morning of cutover only',
      'No communication at all, to avoid alarming them',
    ],
    answer: 'A proactive communication plan specifically addressing their needs and timing',
    explanation: 'High-impact or VIP-affecting changes need deliberate, proactive communication.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-coord-8',
    conceptIds: ['cutover-runbook'],
    type: 'pm-judgment',
    prompt: 'What should a cutover runbook always include?',
    choices: [
      'Sequenced tasks, owners, validation steps, and a rollback action',
      'Only a start time',
      'Only the list of attendees',
      'A marketing summary of the project',
    ],
    answer: 'Sequenced tasks, owners, validation steps, and a rollback action',
    explanation: 'A runbook needs sequencing, ownership, validation, and rollback to be actionable during go-live.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-coord-9',
    conceptIds: ['decision-log', 'action-log'],
    type: 'multiple-choice',
    prompt: 'What is the difference between a decision log and an action log?',
    choices: [
      'A decision log records key choices and rationale; an action log tracks assigned tasks with owners and due dates',
      'They are the same document with different names',
      'An action log only exists after project closeout',
      'A decision log is only used by executives',
    ],
    answer: 'A decision log records key choices and rationale; an action log tracks assigned tasks with owners and due dates',
    explanation: 'Decision logs preserve rationale; action logs track execution of specific tasks.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-coord-10',
    conceptIds: ['scope', 'statement-of-work'],
    type: 'pm-judgment',
    prompt: 'A technical requirement comes up that seems reasonable but was never discussed. What is the first check?',
    choices: [
      'Whether it is covered by the agreed statement of work / scope',
      'Whether it can be finished today',
      'Whether it is technically interesting',
      'Whether the engineer likes the idea',
    ],
    answer: 'Whether it is covered by the agreed statement of work / scope',
    explanation: 'Scope should be checked against the SOW before treating new work as already agreed.',
    sourceIds: ['az900-architecture'],
  },

  // ── Cross-cutting scenario translation ──
  {
    id: 'q-cross-1',
    conceptIds: ['hybrid-identity', 'entra-connect', 'exchange-online', 'conditional-access', 'dns'],
    type: 'pm-judgment',
    prompt: '"The customer is running hybrid identity, Entra Connect is synchronizing users, and Exchange Online licensing needs assigning before a pilot cohort and production cutover." Which item is a technical workstream, not a delivery control?',
    choices: ['Entra Connect sync', 'Pilot mailbox cohort', 'Production cutover date', 'Change control'],
    answer: 'Entra Connect sync',
    explanation: 'Entra Connect sync is identity/technical work; pilot cohort and cutover date are delivery controls; change control is a coordination process.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-cross-2',
    conceptIds: ['conditional-access', 'entra-id'],
    type: 'placement',
    prompt: 'On the ecosystem map, which layer does Conditional Access sit in?',
    choices: ['Identity & Access', 'Azure Platform', 'Endpoint', 'Operations/Delivery'],
    answer: 'Identity & Access',
    explanation: 'Conditional Access is part of the cross-cutting identity layer built on Entra ID.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-cross-3',
    conceptIds: ['intune'],
    type: 'placement',
    prompt: 'On the ecosystem map, which layer does Intune sit in?',
    choices: ['Endpoint', 'Business/Users', 'Security/Governance', 'Azure Platform'],
    answer: 'Endpoint',
    explanation: 'Intune is the primary endpoint management layer service.',
    sourceIds: ['m365-admin-path'],
  },
  {
    id: 'q-cross-4',
    conceptIds: ['sentinel'],
    type: 'placement',
    prompt: 'On the ecosystem map, which layer does Microsoft Sentinel sit in?',
    choices: ['Security/Governance', 'Endpoint', 'Business/Users', 'Operations/Delivery'],
    answer: 'Security/Governance',
    explanation: 'Sentinel is part of the security and governance layer.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-cross-5',
    conceptIds: ['m365-admin-center'],
    type: 'placement',
    prompt: 'On the ecosystem map, which layer do admin centers and service health sit in?',
    choices: ['Operations/Delivery overlay', 'Identity & Access', 'Azure Platform', 'Endpoint'],
    answer: 'Operations/Delivery overlay',
    explanation: 'Admin centers, service health, licensing, and change control sit in the operations/delivery overlay.',
    sourceIds: ['m365-admin-path'],
  },

  // ── Acronym recognition sweep ──
  {
    id: 'q-acr-1',
    conceptIds: ['rbac'],
    type: 'acronym',
    prompt: 'What does RBAC stand for?',
    choices: ['Role-Based Access Control', 'Remote Backup and Compliance', 'Resource-Based Audit Control', 'Role-Based Authorization Center'],
    answer: 'Role-Based Access Control',
    explanation: 'RBAC assigns permissions via roles rather than per-user, per-resource grants.',
    sourceIds: ['az900-governance'],
  },
  {
    id: 'q-acr-2',
    conceptIds: ['iaas-paas-saas'],
    type: 'acronym',
    prompt: 'What does IaaS stand for?',
    choices: ['Infrastructure as a Service', 'Identity as a Service', 'Integration as a Service', 'Internet as a Service'],
    answer: 'Infrastructure as a Service',
    explanation: 'IaaS provides raw compute, network, and storage resources.',
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'q-acr-3',
    conceptIds: ['mdm'],
    type: 'acronym',
    prompt: 'What does MDM stand for?',
    choices: ['Mobile Device Management', 'Managed Data Migration', 'Multi-Domain Membership', 'Mobile Data Monitoring'],
    answer: 'Mobile Device Management',
    explanation: 'MDM manages the full device.',
    sourceIds: ['m365-admin-path'],
  },
  {
    id: 'q-acr-4',
    conceptIds: ['mam'],
    type: 'acronym',
    prompt: 'What does MAM stand for?',
    choices: ['Mobile Application Management', 'Managed Access Model', 'Multi-Account Membership', 'Mobile Authentication Method'],
    answer: 'Mobile Application Management',
    explanation: 'MAM manages specific apps and their data, not the whole device.',
    sourceIds: ['m365-admin-path'],
  },
  {
    id: 'q-acr-5',
    conceptIds: ['raid'],
    type: 'acronym',
    prompt: 'What does RAID stand for in a project-tracking context?',
    choices: ['Risks, Assumptions, Issues, Dependencies', 'Redundant Array of Independent Disks', 'Rapid Assessment of Issue Data', 'Risk Analysis and Incident Documentation'],
    answer: 'Risks, Assumptions, Issues, Dependencies',
    explanation: 'In project delivery, RAID is the risk/assumption/issue/dependency tracking framework — a different meaning than the storage term.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-acr-6',
    conceptIds: ['raci'],
    type: 'acronym',
    prompt: 'What does RACI stand for?',
    choices: ['Responsible, Accountable, Consulted, Informed', 'Reviewed, Approved, Closed, Issued', 'Risk, Action, Cost, Impact', 'Responsible, Assigned, Confirmed, Implemented'],
    answer: 'Responsible, Accountable, Consulted, Informed',
    explanation: 'RACI clarifies roles and decision rights on a project.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-acr-7',
    conceptIds: ['csp'],
    type: 'fill-in',
    prompt: 'Fill in the blank: ___ is the Microsoft partner program used to provision and support customer cloud subscriptions.',
    answer: 'CSP',
    explanation: 'CSP (Cloud Solution Provider) is the partner program.',
    sourceIds: ['ms900-licensing-support'],
  },
  {
    id: 'q-acr-8',
    conceptIds: ['dns'],
    type: 'multiple-choice',
    prompt: 'Which DNS record type is commonly used to route email to Exchange Online?',
    choices: ['MX', 'A only', 'PTR', 'AAAA'],
    answer: 'MX',
    explanation: 'MX (mail exchange) records direct where mail for a domain should be delivered.',
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'q-acr-9',
    conceptIds: ['zero-trust', 'conditional-access'],
    type: 'dependency',
    prompt: 'Which Entra ID feature is commonly used to operationalize Zero Trust access decisions?',
    choices: ['Conditional Access', 'Resource locks', 'Azure Policy', 'Cost Management'],
    answer: 'Conditional Access',
    explanation: 'Conditional Access evaluates context and risk to make Zero Trust access decisions in practice.',
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'q-acr-10',
    conceptIds: ['nce-concept'],
    type: 'acronym',
    prompt: 'What does NCE stand for?',
    choices: ['New Commerce Experience', 'Network Configuration Engine', 'National Cloud Entitlement', 'New Client Environment'],
    answer: 'New Commerce Experience',
    explanation: 'NCE is Microsoft\'s modernized licensing and purchasing framework name.',
    sourceIds: ['ms900-licensing-support'],
  },
  {
    id: 'q-acr-11',
    conceptIds: ['compute'],
    type: 'multiple-choice',
    prompt: 'What is a common first step when moving an on-prem server workload to Azure with minimal redesign?',
    choices: ['Lift-and-shift into an Azure VM (IaaS)', 'Immediately rewrite it as a serverless function', 'Delete it and start over', 'Move it to SharePoint'],
    answer: 'Lift-and-shift into an Azure VM (IaaS)',
    explanation: 'A lift-and-shift to IaaS is a common low-redesign first migration step, sometimes followed later by re-platforming.',
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'q-acr-12',
    conceptIds: [],
    type: 'multiple-choice',
    prompt: 'Which of these is an active Microsoft certification, per this app\'s source baseline (September 2026)?',
    choices: ['AZ-900', 'MS-900', 'Neither is active', 'Both are equally active'],
    answer: 'AZ-900',
    explanation: 'AZ-900 (Azure Fundamentals) is active. MS-900 was retired by Microsoft on March 31, 2026 — always verify current status against the Sources view.',
    sourceIds: ['az900-cert', 'ms900-study-guide'],
  },
  {
    id: 'q-acr-13',
    conceptIds: [],
    type: 'multiple-choice',
    prompt: 'Is AB-900 an official one-for-one replacement for the retired MS-900 exam?',
    choices: [
      'Not confirmed as such by Microsoft — it is current M365 beginner/admin material, not a stated replacement',
      'Yes, Microsoft explicitly states this',
      'AB-900 replaced AZ-900, not MS-900',
      'MS-900 was never retired',
    ],
    answer: 'Not confirmed as such by Microsoft — it is current M365 beginner/admin material, not a stated replacement',
    explanation: 'This app does not claim AB-900 is a direct replacement for MS-900 unless an official Microsoft source explicitly says so.',
    sourceIds: ['ab900-what-is-m365', 'ms900-study-guide'],
  },
]

export const questionById = new Map(questions.map((q) => [q.id, q]))
