import type { Source } from './types'

// Source baseline used across this application. Volatile facts (licensing,
// exam status, product naming, pricing) must link back here and carry a
// "verify current information" note in the UI — see VerifyBadge.
export const SOURCE_BASELINE_DATE = '2026-09-01'

export const sources: Source[] = [
  {
    id: 'az900-cert',
    title: 'Microsoft Certified: Azure Fundamentals (AZ-900)',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/',
    type: 'official-microsoft',
    lastVerified: SOURCE_BASELINE_DATE,
    status: 'active_certification',
    notes: 'Active Microsoft certification as of the source baseline date used in this project.',
  },
  {
    id: 'az900-cloud-concepts',
    title: 'AZ-900: Describe cloud concepts',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/',
    type: 'official-microsoft',
    lastVerified: SOURCE_BASELINE_DATE,
  },
  {
    id: 'az900-architecture',
    title: 'AZ-900: Describe Azure architecture and services',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/paths/azure-fundamentals-describe-azure-architecture-services/',
    type: 'official-microsoft',
    lastVerified: SOURCE_BASELINE_DATE,
  },
  {
    id: 'az900-governance',
    title: 'AZ-900: Describe Azure management and governance',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/paths/describe-azure-management-governance/',
    type: 'official-microsoft',
    lastVerified: SOURCE_BASELINE_DATE,
  },
  {
    id: 'az900-guided-projects',
    title: 'Introduction to cloud infrastructure: apply Azure skills in guided projects',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/paths/introduction-cloud-infrastructure-apply-azure-skills-guided-projects/',
    type: 'official-microsoft',
    lastVerified: SOURCE_BASELINE_DATE,
  },
  {
    id: 'ms900-study-guide',
    title: 'MS-900 study guide (legacy)',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ms-900',
    type: 'official-microsoft',
    lastVerified: SOURCE_BASELINE_DATE,
    status: 'retired_certification_material',
    retiredDate: '2026-03-31',
    notes: 'Microsoft retired Exam MS-900 on March 31, 2026. Kept only as legacy foundational reading — never presented as an active credential.',
  },
  {
    id: 'ms900-licensing-support',
    title: 'Microsoft 365 licensing, service, and support concepts (legacy MS-900 path)',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/paths/m365-licensing-service-support/',
    type: 'official-microsoft',
    lastVerified: SOURCE_BASELINE_DATE,
    status: 'retired_certification_material',
    retiredDate: '2026-03-31',
  },
  {
    id: 'ab900-what-is-m365',
    title: 'What is Microsoft 365? (AB-900 current material)',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/modules/what-is-m365/',
    type: 'official-microsoft',
    lastVerified: SOURCE_BASELINE_DATE,
    status: 'active',
    notes: 'Current Microsoft 365 beginner/admin material. Not confirmed by Microsoft as a one-for-one replacement for the retired MS-900 — do not present it that way.',
  },
  {
    id: 'm365-admin-path',
    title: 'Explore Microsoft 365 administration',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/paths/explore-microsoft-365-administration/',
    type: 'official-microsoft',
    lastVerified: SOURCE_BASELINE_DATE,
  },
  {
    id: 'sc900-cert',
    title: 'Microsoft Certified: Security, Compliance, and Identity Fundamentals (SC-900)',
    publisher: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/credentials/certifications/security-compliance-and-identity-fundamentals/',
    type: 'official-microsoft',
    lastVerified: SOURCE_BASELINE_DATE,
    status: 'active_certification',
  },
  {
    id: 'tt-contact',
    title: 'TrustedTech — Contact',
    publisher: 'TrustedTech',
    url: 'https://www.trustedtechteam.com/pages/contact-us',
    type: 'company',
    lastVerified: SOURCE_BASELINE_DATE,
  },
  {
    id: 'tt-m365-blog',
    title: 'TrustedTech — Microsoft 365 blog',
    publisher: 'TrustedTech',
    url: 'https://www.trustedtechteam.com/blogs/microsoft-365',
    type: 'company',
    lastVerified: SOURCE_BASELINE_DATE,
  },
  {
    id: 'tt-azure-blog',
    title: 'TrustedTech — Azure blog',
    publisher: 'TrustedTech',
    url: 'https://www.trustedtechteam.com/blogs/azure',
    type: 'company',
    lastVerified: SOURCE_BASELINE_DATE,
  },
  {
    id: 'tt-product-resources',
    title: 'TrustedTech — Product resources',
    publisher: 'TrustedTech',
    url: 'https://www.trustedtechteam.com/pages/product-resources',
    type: 'company',
    lastVerified: SOURCE_BASELINE_DATE,
  },
  {
    id: 'tt-strategic-partners',
    title: 'TrustedTech — Strategic partners',
    publisher: 'TrustedTech',
    url: 'https://www.trustedtechteam.com/pages/strategic-partners',
    type: 'company',
    lastVerified: SOURCE_BASELINE_DATE,
  },
  {
    id: 'sim-scenario-lab',
    title: 'Scenario Lab simulated customer situations',
    publisher: 'This application',
    url: '',
    type: 'simulation',
    lastVerified: SOURCE_BASELINE_DATE,
    notes: 'Not real customer data. Built for applied reasoning practice; facts are fixed by design, not AI-generated at runtime.',
  },
  {
    id: 'user-authored',
    title: 'User-authored note',
    publisher: 'You',
    url: '',
    type: 'user-note',
    lastVerified: SOURCE_BASELINE_DATE,
    notes: 'Entered by the learner. Not verified, not a source of fact for the app.',
  },
]

export const sourceById = new Map(sources.map((s) => [s.id, s]))
