import type { LearningModule, Track } from './types'

export const tracks: Track[] = [
  {
    id: 'it-foundation',
    code: 'A',
    title: 'IT Foundation',
    description: 'The baseline vocabulary underneath every other track: client/server, network, identity basics, data, and resiliency.',
    domain: 'foundation',
    moduleIds: ['found-core', 'found-network', 'found-data', 'found-resiliency'],
  },
  {
    id: 'cloud-az900',
    code: 'B',
    title: 'Cloud / AZ-900',
    description: 'Core Azure cloud concepts, architecture, and governance aligned to the active AZ-900 certification.',
    domain: 'cloud',
    moduleIds: ['cloud-concepts', 'cloud-architecture', 'cloud-governance'],
  },
  {
    id: 'm365-track',
    code: 'C',
    title: 'Microsoft 365',
    description: 'The productivity and collaboration workloads customers most often ask a coordinator about.',
    domain: 'm365',
    moduleIds: ['m365-ecosystem-mod', 'm365-admin-mod'],
  },
  {
    id: 'identity-track',
    code: 'D',
    title: 'Identity',
    description: 'AD DS, Entra ID, hybrid identity, and the access controls built on top of them.',
    domain: 'identity',
    moduleIds: ['identity-foundations', 'identity-access-control'],
  },
  {
    id: 'endpoint-track',
    code: 'E',
    title: 'Endpoint Management',
    description: 'Intune, MDM/MAM, enrollment, and how endpoint state connects to Conditional Access.',
    domain: 'endpoint',
    moduleIds: ['endpoint-mgmt'],
  },
  {
    id: 'security-track',
    code: 'F',
    title: 'Security',
    description: 'Zero Trust, the Defender family, Sentinel, and Purview at a conceptual level.',
    domain: 'security',
    moduleIds: ['security-fundamentals'],
  },
  {
    id: 'migration-track',
    code: 'G',
    title: 'Migration Delivery',
    description: 'The lifecycle every migration project moves through, from discovery to decommission.',
    domain: 'migration',
    moduleIds: ['migration-lifecycle'],
  },
  {
    id: 'licensing-track',
    code: 'H',
    title: 'Licensing / CSP',
    description: 'CSP, SKUs, and license assignment at a conceptual level — always paired with a verification note.',
    domain: 'licensing',
    moduleIds: ['licensing-csp-mod'],
  },
  {
    id: 'coordination-track',
    code: 'I',
    title: 'IT Project Coordination',
    description: 'The delivery-control vocabulary: scope, RAID, RACI, change control, cutover, and communications.',
    domain: 'coordination',
    moduleIds: ['coordination-core', 'coordination-delivery'],
  },
]

export const modules: LearningModule[] = [
  {
    id: 'found-core',
    trackId: 'it-foundation',
    title: 'Client/Server, Endpoints, and Applications',
    summary: 'The basic model of how devices, applications, and services relate.',
    prerequisites: [],
    conceptIds: ['client-server', 'endpoint-device', 'operating-system', 'application', 'api'],
    objectives: ['Explain the client/server model in plain language', 'Distinguish an endpoint, an OS, and an application'],
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'found-network',
    trackId: 'it-foundation',
    title: 'Network, IP, DNS, and Directory',
    summary: 'How devices find and trust each other on a network.',
    prerequisites: ['found-core'],
    conceptIds: ['network', 'ip-addressing', 'dns', 'directory-services', 'authentication', 'authorization'],
    objectives: ['Explain why DNS matters to a migration project', 'Distinguish authentication from authorization'],
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'found-data',
    trackId: 'it-foundation',
    title: 'Data, Logs, and Backup',
    summary: 'How systems store, observe, and protect data.',
    prerequisites: ['found-core'],
    conceptIds: ['database', 'logs', 'backup'],
    objectives: ['Explain why validation relies on logs', 'Explain why a completed backup is not the same as a restorable one'],
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'found-resiliency',
    trackId: 'it-foundation',
    title: 'High Availability, DR, RPO/RTO',
    summary: 'How systems stay up, and how they recover when they don\'t.',
    prerequisites: ['found-data'],
    conceptIds: ['high-availability', 'disaster-recovery', 'rpo', 'rto'],
    objectives: ['Explain the difference between RPO and RTO', 'Explain why HA and DR are related but distinct goals'],
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'cloud-concepts',
    trackId: 'cloud-az900',
    title: 'Cloud Deployment and Service Models',
    summary: 'On-prem vs. cloud vs. hybrid, shared responsibility, and IaaS/PaaS/SaaS.',
    prerequisites: ['found-network'],
    conceptIds: ['cloud-deployment-models', 'shared-responsibility', 'iaas-paas-saas', 'consumption-model'],
    objectives: ['Explain the shared responsibility model', 'Identify which service model a given workload uses'],
    sourceIds: ['az900-cloud-concepts'],
  },
  {
    id: 'cloud-architecture',
    trackId: 'cloud-az900',
    title: 'Azure Architecture Hierarchy',
    summary: 'Tenant, management group, subscription, resource group, resource.',
    prerequisites: ['cloud-concepts'],
    conceptIds: ['azure-regions', 'azure-tenant', 'management-group', 'azure-subscription', 'resource-group', 'azure-resource', 'compute', 'networking', 'vnet', 'storage', 'azure-database'],
    objectives: ['Draw the Azure hierarchy from tenant down to resource', 'Explain how compute, networking, and storage relate'],
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'cloud-governance',
    trackId: 'cloud-az900',
    title: 'Azure Governance and Management',
    summary: 'RBAC, Azure Policy, resource locks, monitoring, and cost management.',
    prerequisites: ['cloud-architecture'],
    conceptIds: ['rbac', 'azure-policy', 'resource-locks', 'azure-monitor', 'cost-management'],
    objectives: ['Explain how RBAC and Azure Policy differ', 'Explain why cost ownership should be assigned before project closeout'],
    sourceIds: ['az900-governance'],
  },
  {
    id: 'm365-ecosystem-mod',
    trackId: 'm365-track',
    title: 'Microsoft 365 Workloads',
    summary: 'Exchange Online, Teams, SharePoint, OneDrive, and Microsoft 365 Apps.',
    prerequisites: ['cloud-concepts'],
    conceptIds: ['m365-ecosystem', 'exchange-online', 'teams', 'sharepoint-online', 'onedrive', 'm365-apps'],
    objectives: ['Explain the difference between OneDrive and SharePoint Online', 'List the workloads typically in scope for a Google Workspace migration'],
    sourceIds: ['ab900-what-is-m365'],
  },
  {
    id: 'm365-admin-mod',
    trackId: 'm365-track',
    title: 'Microsoft 365 Administration',
    summary: 'The admin center, delegated roles, and service health.',
    prerequisites: ['m365-ecosystem-mod'],
    conceptIds: ['m365-admin-center', 'service-health'],
    objectives: ['Explain what to check before escalating a cutover issue as a project defect'],
    sourceIds: ['m365-admin-path'],
  },
  {
    id: 'identity-foundations',
    trackId: 'identity-track',
    title: 'AD DS, Entra ID, and Hybrid Identity',
    summary: 'The identity architecture underneath most Microsoft 365 and Azure projects.',
    prerequisites: ['found-network'],
    conceptIds: ['ad-ds', 'entra-id', 'hybrid-identity', 'entra-connect'],
    objectives: ['Explain hybrid identity in one sentence', 'Explain what Entra Connect actually synchronizes'],
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'identity-access-control',
    trackId: 'identity-track',
    title: 'Access Control: MFA, SSO, Conditional Access',
    summary: 'The controls layered on top of authentication.',
    prerequisites: ['identity-foundations'],
    conceptIds: ['mfa', 'sso', 'conditional-access', 'least-privilege'],
    objectives: ['Explain what to clarify before broad Conditional Access enforcement', 'Explain why a break-glass account matters'],
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'endpoint-mgmt',
    trackId: 'endpoint-track',
    title: 'Intune, MDM/MAM, and Autopilot',
    summary: 'How devices get enrolled, configured, and made compliant.',
    prerequisites: ['identity-access-control'],
    conceptIds: ['intune', 'mdm', 'mam', 'enrollment', 'compliance-policy', 'configuration-profiles', 'autopilot'],
    objectives: ['Explain the difference between MDM and MAM', 'Explain why compliance should be validated before it gates access'],
    sourceIds: ['m365-admin-path'],
  },
  {
    id: 'security-fundamentals',
    trackId: 'security-track',
    title: 'Zero Trust, Defender, Sentinel, Purview',
    summary: 'The security product family and the model behind it, at a conceptual level.',
    prerequisites: ['identity-access-control'],
    conceptIds: ['zero-trust', 'defender-family', 'defender-endpoint', 'defender-office', 'defender-cloud', 'sentinel', 'siem', 'purview'],
    objectives: ['Explain Zero Trust in plain language', 'Distinguish a SIEM from a SOC'],
    sourceIds: ['sc900-cert'],
  },
  {
    id: 'migration-lifecycle',
    trackId: 'migration-track',
    title: 'Discover Through Decommission',
    summary: 'The full migration lifecycle and its delivery controls.',
    prerequisites: ['cloud-architecture', 'identity-foundations'],
    conceptIds: [
      'discover-phase', 'assess-phase', 'design-phase', 'pilot-phase', 'cutover',
      'validate-phase', 'stabilize-hypercare', 'decommission', 'rollback',
      'maintenance-window', 'acceptance-criteria',
    ],
    objectives: ['Sequence the migration lifecycle from discovery to decommission', 'Explain why hypercare needs defined exit criteria'],
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'licensing-csp-mod',
    trackId: 'licensing-track',
    title: 'CSP, SKUs, and License Assignment',
    summary: 'Conceptual licensing vocabulary. Exact entitlements must always be verified.',
    prerequisites: ['m365-ecosystem-mod'],
    conceptIds: ['csp', 'sku', 'license-assignment', 'nce-concept'],
    objectives: ['Explain why licensing can block a technically ready project', 'Explain what a term commitment can constrain'],
    sourceIds: ['ms900-licensing-support'],
  },
  {
    id: 'coordination-core',
    trackId: 'coordination-track',
    title: 'Scope, RAID, and RACI',
    summary: 'The core tracking vocabulary of project delivery.',
    prerequisites: [],
    conceptIds: ['scope', 'statement-of-work', 'raid', 'raci', 'decision-log', 'action-log'],
    objectives: ['Classify a situation as a risk, assumption, issue, or dependency', 'Explain the difference between Responsible and Accountable in RACI'],
    sourceIds: ['az900-architecture'],
  },
  {
    id: 'coordination-delivery',
    trackId: 'coordination-track',
    title: 'Change Control, Cutover, and Communications',
    summary: 'Delivery controls that keep a project on track through go-live.',
    prerequisites: ['coordination-core', 'migration-lifecycle'],
    conceptIds: ['change-control', 'communication-plan', 'cutover-runbook'],
    objectives: ['Explain when a request needs change control versus normal execution', 'Build a basic cutover runbook structure'],
    sourceIds: ['az900-architecture'],
  },
]

export const trackById = new Map(tracks.map((t) => [t.id, t]))
export const moduleById = new Map(modules.map((m) => [m.id, m]))
export const modulesByTrack = (trackId: string) => modules.filter((m) => m.trackId === trackId)
